### ISSUE TITLE
Story Link Broken if you use "Open link in new window"

### ISSUE THREAD

**Issue by fd0cwp** [microsoft/azure-boards-estimate#105]
Please see "Story Link Broken for Other Users in Session" #77 and "Workitem link targets a wrong base address with on-premise configuration" #37.

Installed version: 2.3.21 

It now works fine if you just click on the link. But if you shift click or right click and select "Open link in new window", the previously selected work item opens. You can see this already in the link preview (lower left corner in Chrome).

Maybe just an update is missing after selecting another card?

**Comment by AminTi** [comment]
We are working to resolve the problem as quickly as possible.
Thank you for your patience
