### ISSUE TITLE
When connecting to Estimate session it's asking to login after entering correct login it asks again 

### ISSUE THREAD

**Issue by edisonas** [microsoft/azure-boards-estimate#112]
When connecting to Estimate session it's asking to login after entering correct login it asks again and again and never stops.
![Capture](https://user-images.githubusercontent.com/72611099/159951339-22fb884d-4964-4f19-8d6e-a1d786ec84cf.PNG)

**Comment by NmathieuAdista** [comment]
Same probleme !

This error appear in Console : 
![image](https://user-images.githubusercontent.com/72745901/161498990-01086676-c483-4f24-96dc-c42cd54d3f5a.png)

Help me :)

**Comment by AminTi** [comment]
Thanks for reporting, we will take review. 
@edisonas  @NmathieuAdista

**Comment by AminTi** [comment]
Thanks for reporting, we will review these issues.
@NmathieuAdista  @edisonas

**Comment by edisonas** [comment]
Hi @AminTi, let me know which logs you need from the browser F12? and which ones from the console log?

**Comment by edisonas** [comment]
@AminTi , did you found anything more on that? Thanks

**Comment by dusoxr** [comment]
Same thread here: https://github.com/microsoft/azure-boards-estimate/issues/83

**Comment by AminTi** [comment]
We have a new release coming this week. Let's see if that resolves the issue, else we'll dig into this again.
@edisonas

**Comment by echalone** [comment]
Same problem here, but only with Google Chrome, not with Mozilla Firefox.
Chrome console has 401 errors for URL  "<CollectionUrl>/_apis/wit/workItemIcons" when login is canceled, so I'm assuming that's where the problem is.

**Comment by edisonas** [comment]
@AminTi , so how about new release? When it going to happen? Thanks.

**Comment by AminTi** [comment]
HI @edisonas @dusoxr  @echalone we released an update today, try again and let me know if you still facing the same issues.

**Comment by echalone** [comment]
> HI @edisonas @dusoxr @echalone we released an update today, try again and let me know if you still facing the same issues.

Hi, yes we too still have the same issue. Same 401 when trying to access sub-url URL "/_apis/wit/workItemIcons" of Azure DevOps Server On-Premis. We're still using Azure DevOps Server Version 2019 if that's important.

**Comment by JonHershey** [comment]
Also running into the issue running 2019 (17.M153.5) on-premise, with 2.3.29 installed.

Is it possible it got introduced when moving around the API version?
from: "azure-devops-extension-api": "1.152.3"
to: "azure-devops-extension-api": "1.158.0"
to: "azure-devops-extension-api": "1.152.0"

I haven't been able to track down what changed from .0 to .3.

Our UAT has 2.3.1 installed (turned auto updates off and rolled back), that version is working correctly.

**Comment by edisonas** [comment]
@AminTi @dusoxr , so what you suggest further on it? Thanks

**Comment by echalone** [comment]
I just had to make a test update of our Azure DevOps Server from 2019 to 2020 and the issue seems to be gone then. So that too speaks for a 2019 issue.

**Comment by klsgrtx** [comment]
My team is also running an on-prem instance of 2019 and seeing this behavior with v2.3.29
Is there a way to roll back to the previous version until a fix is provided?
Or is the requirement to upgrade to 2020?

**Comment by AminTi** [comment]
Hi @klsgrtx  test update of our Azure DevOps Server from 2019 to 2020 resolved the problem for @echalone.

**Comment by klsgrtx** [comment]
@AminTi - ok thanks.
Unfortunately, we're not in a position to do a TFS upgrade to 2020 at this time.

**Comment by klsgrtx** [comment]
> 

I just did a test using MS Edge (I no longer have access to FireFox).
The login prompt is presented, but I was able to cancel and proceed with working in the estimate.

However, even though I click cancel and appear to have the ability to proceed, I see numerous errors in the console like this:
Fetch.js:274 
        
       Uncaught (in promise) TFS.WebApi.Exception: TF400813: The user 'ebc9c185-f41c-4cb9-83ba-b0a88ddf3438' is not authorized to access this resource.
    at Object.<anonymous> (http://<SERVERNAME>/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/estimate/2.3.29/assetbyname/build/static/js/1.31d85ca2.chunk.js:1:831728)
    at http://<SERVERNAME>/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/estimate/2.3.29/assetbyname/build/static/js/1.31d85ca2.chunk.js:1:830251
    at Object.next (http://<SERVERNAME>/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/estimate/2.3.29/assetbyname/build/static/js/1.31d85ca2.chunk.js:1:830356)
    at a (http://<SERVERNAME>/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/estimate/2.3.29/assetbyname/build/static/js/1.31d85ca2.chunk.js:1:829101)
    
    When I try to duplicate this in Chrome, I'm no longer getting the login prompt, but simply this message:
    
Could not load session: TF400893: Unable to contact the server. Please check your network connection and try again.

And this from the console:
uncaught at Gn at Gn 
 at d 
 at Zn 
 NetworkException: TF400893: Unable to contact the server. Please check your network connection and try again.
    at Object.<anonymous> (https://<SERVERNAME>/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/estimate/2.3.29/assetbyname/build/static/js/1.31d85ca2.chunk.js:1:831468)
    at https://<SERVERNAME>/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/estimate/2.3.29/assetbyname/build/static/js/1.31d85ca2.chunk.js:1:830251
    at Object.throw (https://<SERVERNAME>/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/estimate/2.3.29/assetbyname/build/static/js/1.31d85ca2.chunk.js:1:830356)
    at s (https://<SERVERNAME>/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/estimate/2.3.29/assetbyname/build/static/js/1.31d85ca2.chunk.js:1:829152)

**Comment by klsgrtx** [comment]
Also found that if I keep refreshing my browser and/or clearing the cache that on occasion I can get the page to load without prompting me to login or showing the "unable to contact server" message.

But I see numerous 400 and 404 errors in the console

**Comment by edisonas** [comment]
@AminTi, so the only way to resolve that for 2019 version is to upgrade to 2020?

**Comment by klsgrtx** [comment]
> @AminTi, so the only way to resolve that for 2019 version is to upgrade to 2020?

@AminTi  - is there not a way to download a previous release and use that until my team is in a position to upgrade to 2020?
Upgrading for the sake of an extension doesn't seem practical, especially in large enterprise environments.

**Comment by echalone** [comment]
Estimate Version 2.3.1 is the last one that still works with Azure DevOps Server 2019, I have uploaded it to one of my repositories and its vsix can now be downloaded here: https://github.com/echalone/files/blob/main/AzureDevOps/Extensions/Estimate/Estimate-v2.3.1.vsix?raw=true

Uninstall Estimate from your collection and afterwards from your server, then reinstall Estimate with the vsix for version 2.3.1 as provided in my repository for server and collection. Should work again afterwards.

**Comment by edisonas** [comment]
Thank you @echalone! That works for me. After we install 2.3.1, I suspect it will not upgrade automatically to the never version?

**Comment by echalone** [comment]
I think that only happens when you install from marketplace instead of manually installing it by vsix upload? But don't quote me on that ^^ if it automatically updates we'll have the same problem again too xD
