### ISSUE TITLE
Azure DevOps Retrospective Extension: (1) Default Story Point of 3 (2) Voting issues (3) Grouping issues

### ISSUE THREAD

**Issue by NataliaLuiz** [microsoft/azure-boards-estimate#114]
Hi @[AminTi](https://github.com/AminTi) 👍 

I have 3 issues that I need you to assist me with please: 

1. When creating a new User Story the default Story Point is 3. **How can I change this?**
![image](https://user-images.githubusercontent.com/102977105/161571507-650fd027-117b-43ea-ac78-2f8c669a40ae.png)

3. I have given my teams members 10 votes each, but sometimes they can only vote 8 or 11 times. **How can I resolve this?**
![image](https://user-images.githubusercontent.com/102977105/161571025-0952516e-1635-46f0-a96e-a68b9e4659ef.png)

4. Some of my team members cannot group tiles. **How can I resolve this?**
![image](https://user-images.githubusercontent.com/102977105/161571148-cf6c3ab9-0c6a-4ac3-82d2-86213e31c946.png)

Thank you SO much!!

**Comment by byamagata** [comment]
@NataliaLuiz 
I’m not @AminTi  but I’m pretty sure that none of these are issues with the estimation poker add on but rather they are things to resolve in ADO. 
the first is your default settings for new work items, the other two are issues with retrospectives. 

I don’t think this is the right place.

**Comment by NataliaLuiz** [comment]
> @NataliaLuiz I’m not @AminTi but I’m pretty sure that none of these are issues with the estimation poker add on but rather they are things to resolve in ADO. the first is your default settings for new work items, the other two are issues with retrospectives.
> 
> I don’t think this is the right place.

Hi @byamagata,

I resolved the default story points of 3 in the default settings - thank you SO much for that!! 👍 

Am contacting Retorpestcive Extenstion on their GitHub page. 

Thank you SO MUCH again for the help! 👍
