### ISSUE TITLE
I cannot close or end the sessions in Estimate, can you help, please?

### ISSUE THREAD

**Issue by VS9999** [microsoft/azure-boards-estimate#118]
Hi, how can I get rid of the past sessions in Estimate? There are a lot of sessions that I would like to delete. When I click on "End session", nothing happens.

They were created by a team member who is leaving, I am taking over and would like to get rid of the past sessions.

How do I do that?

Thank you

**Comment by AminTi** [comment]
Thanks for reporting, try this.

![Screenshot 2022-04-25 at 13 03 55 (2)](https://user-images.githubusercontent.com/54841342/165078011-70f8e3f2-f43c-4605-904d-272afb4e2860.png)
![Screenshot 2022-04-25 at 13 08 38 (2)](https://user-images.githubusercontent.com/54841342/165078023-84894e97-107d-44f1-b7bd-48095a52e139.png)

 if you still have the same problem, help us track this down by checking the browser network log (F12 in the browser), and the console log for errors (screenshot).

**Comment by VS9999** [comment]
Hi, it is not working, after I confirm "End session"

![image](https://user-images.githubusercontent.com/104055981/165098355-41accaef-b323-4738-af93-a748a609f8a9.png)

![image](https://user-images.githubusercontent.com/104055981/165098545-5ebb1116-0357-4d1c-bd66-aa30386b707f.png)

**Comment by AminTi** [comment]
Thanks for reporting. We'll dig into this.

**Comment by VS9999** [comment]
I still have the same issue, sessions cannot be closed!
![2022-08-12 14_43_10-Estimate - Boards](https://user-images.githubusercontent.com/104055981/184356495-01f814c2-0193-4479-b9d0-384fae2f9b2a.png)

**Comment by AminTi** [comment]
Do you want to have a web
session looking at it now ?

**Comment by VS9999** [comment]
yes, we can. Can you invite me, please?

**Comment by AminTi** [comment]
I can do it you, can you please send your Email

**Comment by VS9999** [comment]
veronika.sonter@oriflame.com

**Comment by AminTi** [comment]
Did you received my invite?

**Comment by VS9999** [comment]
I did not, it might be quarantined by the company. I will send you a different email. veronika.sonter@gmail.com

**Comment by VS9999** [comment]
Hello again,

the extension was reinstalled, we have the latest version, however it still behaves the same. We run Azure DevOps on cloud. Here is the latest error after trying to delete a session:
![image](https://user-images.githubusercontent.com/104055981/184366495-dc5c34de-3f65-4f10-a3d5-d142352e36d9.png)

**Comment by AminTi** [comment]
Thanks , We will look in to this and get back to you sooner.
