### ISSUE TITLE
Unable to publish extension due to: - Incompatible API version (5.1)

### ISSUE THREAD

**Issue by kevinjonna19** [microsoft/azure-boards-estimate#121]
Hi, We're using AzureDevOps Server 2019 and we tried to install this add-ons but run into issue " Unable to publish extension due to: - Incompatible API version (5.1)", does anybody have any suggestion to install this to ADO Server 2019? thanks

**Comment by AminTi** [comment]
Thanks for reporting @kevinjonna19 . We'll dig into this.

**Comment by AminTi** [comment]
It should work, let me know if you still have the same issue.

**Comment by abbottbd** [comment]
@AminTi - we've just come across this same issue using the latest extension from the marketplace.

**Comment by abbottbd** [comment]
@AminTi  this page seems to suggest the 'supported' API version for 2019 is 5.0 - does this mean the extenstion doesn't work with Azure Devops Server 2019? 
https://learn.microsoft.com/en-us/azure/devops/integrate/concepts/rest-api-versioning?view=azure-devops
