### ISSUE TITLE
Custom Card Sets Created from the Top Screen Don't Show Up

### ISSUE THREAD

**Issue by wrstlrlp13** [microsoft/azure-boards-estimate#123]
If you create a Custom Card Set from the Base Screen, it never shows up when 'Starting a new Game'. 
![image](https://user-images.githubusercontent.com/37849960/165824542-48bedd21-b8d8-4711-b67f-1041607d4336.png)

Only card sets created from the 'Start new Game' Screen seem to save and show up in the dropdown.
![image](https://user-images.githubusercontent.com/37849960/165824752-cfb694b9-042a-4851-978f-5e880b18fda3.png)

**Comment by AminTi** [comment]
Hi @wrstlrlp13  current repo belong to Estimate not Estimation Poker
![Screenshot 2022-05-06 at 16 05 09 (2)](https://user-images.githubusercontent.com/54841342/167149556-a72e31d2-029e-40ee-9db4-4a0f678b2888.png)
