### ISSUE TITLE
Unable to Reveal in an Async session

### ISSUE THREAD

**Issue by joelmartinez** [microsoft/azure-boards-estimate#124]
After enough votes have rolled in, I'm trying to reveal everyone's votes so we can settle on an estimate, and am getting the following errors as shown in the browser console. 
![image](https://user-images.githubusercontent.com/90380/166333760-e58d889a-fefa-4005-b846-9c8c82c0a628.png)

When this happens, the entire screen just blanks, and this is blocking the estimation process :(

**Comment by joelmartinez** [comment]
As a follow up ... after narrowing it down, it seems like this was an issue with only one particular User Story. Not sure what may have been different about that particular story, but I just manually added the story points outside of Estimate, and everything else has been working now.

**Comment by AminTi** [comment]
Hi @joelmartinez  thanks for reporting, we released an update today, try again and let me know if you still facing the same issues.
