### ISSUE TITLE
Loading Sessions hang on "Connecting to server..."

### ISSUE THREAD

**Issue by harb37** [microsoft/azure-boards-estimate#126]
When trying to load an estimate session, the wheels spin on this screen.
![image](https://user-images.githubusercontent.com/8600430/168676806-0da7efcb-a359-4c89-95c1-ec51fd6b94f8.png)

This is error that pops up in the Inspector (404 error).
![image](https://user-images.githubusercontent.com/8600430/168677174-855d90f3-c84a-4159-9a8d-7fa4666bd4bd.png)

Side note, we are also impacted by the below issues:
[I cannot close or end the sessions in Estimate](https://github.com/microsoft/azure-boards-estimate/issues/118)
[Could not load session: 404: Not Found](https://github.com/microsoft/azure-boards-estimate/issues/25) <- This is present on several of our sessions.

**Comment by MOlausson** [comment]
@harb37 can you describe your environment? Can you check if you get any errors in the browser console or network log?
