### ISSUE TITLE
Estimate tool breaks when you choose a non-integer estimate (infinity/coffee/question mark) since the average functionality was added

### ISSUE THREAD

**Issue by DajHarms** [microsoft/azure-boards-estimate#14]
It results in a toString error in console until you delete the work item that had the non-numeric estimate selected

**Comment by MOlausson** [comment]
@DajHarms, this is the same issue as #13, we've working on an update so stay tuned.

**Comment by MOlausson** [comment]
We released an update that should resolve this (2.3.1). Closing this issue but feel free to reopen.
