### ISSUE TITLE
Could not load session: 404: Not Found in one project

### ISSUE THREAD

**Issue by cbframe42** [microsoft/azure-boards-estimate#151]
We have multiple projects under a collection. However, we have one project where, when someone clicks on a session, it tells us "Could not load session: 404: Not Found".

![image](https://user-images.githubusercontent.com/5854422/173363905-91a260d6-ccb0-4dcc-90c3-21bb67516db7.png)

Any thoughts on how we can fix this?

**Comment by hangy** [comment]
Probably the same as #25. Can you point out any differences between the projects?

**Comment by AminTi** [comment]
Thanks for reporting, We'll dig into this.
