### ISSUE TITLE
Anyone can reveal cards. Clicking another card resets votes. Cannot change vote

### ISSUE THREAD

**Issue by Hardrada** [microsoft/azure-boards-estimate#162]
Hello, 
Our team has been using this for a while and we like it but it's temperamental. 

1. Anyone can reveal cards. Ideally, only the session owner can reveal the cards
2. Clicking on other cards resets votes. Ideally, votes are tracked or once a vote begins, you cannot start voting on another card without completing or canceling
3. Cannot change vote. Ideally, after we discuss our disparities in our T-Shirt size votes, we want to change our votes for recording purposes before we commit to a size. 

Thanks.

**Comment by AminTi** [comment]
Hi! thanks for reporting. it will be fixed in an upcoming release.
