### ISSUE TITLE
"Loading workitems" process gets stuck on "Connecting to server..." message.

### ISSUE THREAD

**Issue by ecambio** [microsoft/azure-boards-estimate#176]
"Loading workitems" process gets stuck on "Connecting to server..." message.
Environment : ADO Server 2020
Operation : Just opening Estimate plugin page
![2022-09-20 11_39_06-Estimate - Boards](https://user-images.githubusercontent.com/5832232/191224391-b7f65176-0695-4061-afd8-70ad3c734c8d.png)

**Comment by AminTi** [comment]
Thanks for reporting, we'll dig into this.

**Comment by AminTi** [comment]
I just tried to reproduce the issue and it works as expected,  if you  still facing the same issue let me know. We can schedule a Teams meeting.

**Comment by ecambio** [comment]
Yes please, the issue is still there. Just let me remark that the instance is Azure DevOps Server 2020 Update 1.1, I tried with both secure connection (https) and non-secure (http://..:8080) with Chrome and Edge. Same results unfortunately.

**Comment by AminTi** [comment]
Hi yes can you send  invite now ? amin.titi@solidify.dev

**Comment by ecambio** [comment]
Hi, any update on this?
