### ISSUE TITLE
Estimate Sessions issue "only session owner can reveal estimate"

### ISSUE THREAD

**Issue by NinaMichl** [microsoft/azure-boards-estimate#177]
In created and also newly created sessions we experience the message "only session owner can reveal estimate".
While creation we made sure to NOT check the security option "only creator can cahgne work items and commit".
This is really bothering us as the creator is not always present in sessions and we reuse sessions for regular meetings based on a query.
Thanks in advance for support.
Screenshots attached.
![security option](https://user-images.githubusercontent.com/114060919/191452528-ff9bac14-f3b6-4376-89b6-6181311abb5f.png)
![only session owner can reveal estimate](https://user-images.githubusercontent.com/114060919/191452533-43d0cfab-ef2f-4a1b-af39-5c7076691c02.png)

**Comment by c0deape** [comment]
We're seeing the same issue today

**Comment by AminTi** [comment]
Thanks for reporting.

**Comment by NinaMichl** [comment]
Thank you for looking so quickly into that! Do we have to do something special to see the affect? At the moment it seems we are still facing the same issue. Thanks again.

**Comment by AminTi** [comment]
Hi! I removed the feature it should work now

**Comment by AminTi** [comment]
can you invite to a temas metting now ? amin.titi@solidify.dev

**Comment by NinaMichl** [comment]
Hi Amin,

Sorry, I was out of office until today.
Would today 2 or 3 PM fit for you for a teams meeting?

Thanks again.

Regards,
Nina

Nina Michl
Agile Coach / Scrum Master

***@***.***

Sivantos GmbH
Henri-Dunant-Strasse 100
91058 Erlangen
Germany

www.wsa.com<http://www.wsa.com/>

Email: ***@***.******@***.***>

Wonderful Sound for All

***@***.***<https://www.linkedin.com/company/wsaudiology>  ***@***.*** <https://www.instagram.com/wsaudiology/>   ***@***.*** <https://www.youtube.com/channel/UCnEHxxidp26eKGgLwAH_a4g/channels>

**Comment by NinaMichl** [comment]
Thank you - the issue seems to be fixed now - maybe it just took a while in our environment? (OnPremise)

Nina Michl
Agile Coach / Scrum Master

***@***.***

Sivantos GmbH
Henri-Dunant-Strasse 100
91058 Erlangen
Germany

www.wsa.com<http://www.wsa.com/>

Email: ***@***.******@***.***>

Wonderful Sound for All

***@***.***<https://www.linkedin.com/company/wsaudiology>  ***@***.*** <https://www.instagram.com/wsaudiology/>   ***@***.*** <https://www.youtube.com/channel/UCnEHxxidp26eKGgLwAH_a4g/channels>

From: Nina Michl
Sent: Tuesday, September 27, 2022 8:22 AM
To: microsoft/azure-boards-estimate ***@***.***>
Subject: RE: [microsoft/azure-boards-estimate] Estimate Sessions issue "only session owner can reveal estimate" (Issue #177)

Hi Amin,

Sorry, I was out of office until today.
Would today 2 or 3 PM fit for you for a teams meeting?

Thanks again.

Regards,
Nina

Nina Michl
Agile Coach / Scrum Master

***@***.***
Sivantos GmbH
Henri-Dunant-Strasse 100
91058 Erlangen
Germany

www.wsa.com<http://www.wsa.com/>

Email: ***@***.******@***.***>

Wonderful Sound for All

***@***.***<https://www.linkedin.com/company/wsaudiology>  ***@***.*** <https://www.instagram.com/wsaudiology/>   ***@***.*** <https://www.youtube.com/channel/UCnEHxxidp26eKGgLwAH_a4g/channels>
