### ISSUE TITLE
Azure DevOps - Estimate Board - not showing results

### ISSUE THREAD

**Issue by vbhakth** [microsoft/azure-boards-estimate#179]
Hi,

When we use the Azure DevOps - Estimate Board in Offline mode (Work items picked using Query option), to capture the effort estimations for the backlogs :
1) The estimate board does not open up to show the results after 2-3 days
2) if it opens, then the values entered by the team in the estimate board, have disappeared when we check for results

Kindly request your advice on how to have this issue resolved. We would like to utilizing the offline mode of Estimate board to suit our ways of working.

**Comment by AminTi** [comment]
Thanks for reporting, can you describe your environment and check if you get any errors in the browser console or network log?

**Comment by AminTi** [comment]
i
