### ISSUE TITLE
Azure DevOps: Page "Estimate" always loads very lazy - often mutliple reload necessary

### ISSUE THREAD

**Issue by Holger-Damczyk** [microsoft/azure-boards-estimate#186]
Hello Support-Team,

in our Project DAP in Team 2 we’re ALWAYS having trouble loading page “Estimate” in our “Backlog Refinement and Estimate” Meeting!
When we navigate to
[Estimate - Boards (visualstudio.com)](https://daimler.visualstudio.com/DBDDataDev/_apps/hub/ms-devlabs.estimate.estimate-hub#/session/7drfn/Vehicle_Planning)

it mostly loads longer than a minute, often you have to reload again several times and then - when you are lucky - it shows up. It takes us all every time several minutes until all of the participants have this page loaded. Besides that not all the users which are currently on the estimation board are shown on the left hand side of the button “Leave session” (see pic1, we are normally more than 9 people on that page).
Could please someone have a look on this and fix this?

Thank you,
Holger

Pic1
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/117906551/201066425-6b823977-68aa-4cd1-b8f9-fe821f5f5b78.png">

**Comment by AminTi** [comment]
Hi, it works as expected for me. if you are still facing the same issue help us track this down by checking the browser network log (F12 in the browser.
