### ISSUE TITLE
Not able to end a session

### ISSUE THREAD

**Issue by atfyoung** [microsoft/azure-boards-estimate#200]
When a query related to a session is deleted, then there is no way to end a estimate session
Nothing happens when clicking on "End Session".
When trying to open the session, you will see this error: "Couldn't load a session: 404: Not Found"

**Comment by RoulaLombardi** [comment]
Having the same issue as above. Unable to delete a session by clicking end session from main view and from within the session. Getting the same 404 error.

**Comment by AminTi** [comment]
Thanks for reporting, we will review these issues.
Could you help us track this down by checking the browser network log (F12 in the browser), and the console log for errors ?
