### ISSUE TITLE
Work item link no longer working

### ISSUE THREAD

**Issue by pascalberger** [microsoft/azure-boards-estimate#204]
After latest update (probably Jan 9th 2023) the link to the work item (e.g. `Product Backlog Item 123`) points to an invalid URL.

Previously it pointed to `https://dev.azure.com/mytenant/myproject/_workitems/edit/123`, now it points to `https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.3.77/1673287441938/build/index.html#`

**Comment by pascalberger** [comment]
Doing a quick search in repo history I couldn't find anything related to this. When looking at requests done by the extension I see multiple requests failing with a 404, which maybe are related:

```
https://extmgmt.dev.azure.com/mytenant/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/estimate/Data/Scopes/Default/Current/Collections/%24settings/Documents/3a875f79-74bb-4926-816c-0d6310724c2a-field-configuration
https://extmgmt.dev.azure.com/mytenant/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/estimate/Data/Scopes/Default/Current/Collections/EstimationSessions/Documents
https://extmgmt.dev.azure.com/mytenant/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/estimate/Data/Scopes/Default/Current/Collections/sessions/Documents
```

**Comment by AminTi** [comment]
Thanks for reporting. We'll dig into this.

**Comment by AminTi** [comment]
Hi! again, It should be fixed now.

**Comment by pascalberger** [comment]
Thanks 👍  Januar 13th update seems to have fixed it.
