### ISSUE TITLE
Some users are having 401 issue, preventing then to see the sessions.

### ISSUE THREAD

**Issue by henriquezh** [microsoft/azure-boards-estimate#205]
We have recently started using the tool in the ADO SaaS and find out that some users despite having contributor role are not able to see the sessions created for their ADO Team. when doing the traces the only different is a 401 error that I suspect prevent the right access. they seems to be using a proxy to access the tool  so potentially this can be causing the issue. see screenshot.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/57999916/211812160-b81b3ec4-9a25-48de-a103-d667c6b9bd53.png)

can you help us with that?

**Comment by AminTi** [comment]
Thanks for reporting. We'll dig into this.

**Comment by AminTi** [comment]
It works as expected for me. they should try without a proxy/VPN.
