### ISSUE TITLE
Non creator cannot estimate if "only creator can change work items and commit" is ticked 

### ISSUE THREAD

**Issue by nataliia-ckb** [microsoft/azure-boards-estimate#208]
Good morning!

When I create a new session and tick "Only creator can change work items and commit", my colleagues cannot click on any items to estimate them. The new page looks exactly as it should with all the user stories on the left, but you cannot click onto each item to actually see the details on the right side of the screen (when you hover on each item the cursor does not change to pointer).  

I tested this by creating a new session, and asking my colleague to estimate the test work items. Then I asked them to create a new session and I was not able to estimate. Tried in 2 different projects. 

If I create a session and do not tick "Only creator can change work items and commit" - everything works as expected. 

We are on version 2.3.78 and tested again this morning.

**Comment by nataliia-ckb** [comment]
I can see the following error, but not quite sure if it's directly related - it appears both on working and non working pages.

```
{
"$id": "1",
"innerException": null,
"message": "%error=\"1660002\";%:The collection does not exist\r\n%error=\"1660002\";%:The collection does not exist",
"typeName": "Microsoft.VisualStudio.Services.ExtensionManagement.WebApi.DocumentCollectionDoesNotExistException, Microsoft.VisualStudio.Services.ExtensionManagement.WebApi",
"typeKey": "DocumentCollectionDoesNotExistException",
"errorCode": 0,
"eventId": 3000
}
```

**Comment by AminTi** [comment]
Hi!  when you choose  "Only creator can change" your colleagues can only vote. only the session owner can reveal change items etc...

**Comment by nataliia-ckb** [comment]
@AminTi they cannot vote, as they cannot open the item at all. Have a look at the screen recording https://user-images.githubusercontent.com/104978004/213208061-7300ede8-6d9e-4fa3-bdcb-bd052f8d3532.mov. This is a test session created by my colleague where she selected "only creator can estimate". As a result, I cannot open any of the cards to actually vote on them.  

I was also poking the responses now and where I have created the session **onlyCreatorCanSwitch** variable is set to True and I can switch between items. But where my colleague has created the session with identical settings **onlyCreatorCanSwitch** variable is set to False and I cannot switch items at all.

**Comment by AminTi** [comment]
@nataliia-ckb  I just test it now and it work as expected, can we have a web session now amin.titi@solidify.dev

**Comment by nataliia-ckb** [comment]
@AminTi hey! Thank you very much for the new version! Unfortunately, just tested and getting the same issue :( Checked the commits and can't see the fix relating to this - maybe it got forgotten?

**Comment by AminTi** [comment]
which one of those extensions do you use?
![Screenshot 2023-02-07 at 17 24 13](https://user-images.githubusercontent.com/54841342/217303467-54dd3ae0-2887-42ac-9a1f-7b4d85b9ff32.png)

**Comment by nataliia-ckb** [comment]
Oh, we are on Estimate. Should I try the Poker one?

**Comment by AminTi** [comment]
that's why this repo belongs to Estimate, not the poker one.

**Comment by nataliia-ckb** [comment]
So I am using the right one. We are on the Estimate module :). I can see the "clear" field changes with the new update and already used it. However there seems to be no PR for this item in the code itself :(

**Comment by AminTi** [comment]
my bad, do you use VPN ?, I can not reproduce the issue, amin.titi@solidify.dev  we can do a web session if you want.

- session created by my colleague where she selected "only creator can estimate". As a result, I cannot open any of the cards to actually vote on them  - this is correct  you can not click on any card.

**Comment by nataliia-ckb** [comment]
Thank you so much for looking into this. Let me just try to describe all the steps, maybe I missed something obvious. No VPN. Using Chrome 109.0.5414.119 (although tested in Safari initially and the same behaviour).
Version:
<img width="868" alt="Screenshot 2023-02-08 at 15 29 21" src="https://user-images.githubusercontent.com/104978004/217574791-f685f438-227f-42a6-ae45-853e3784bfdf.png">

I could be wrong, but to me it looks like state management is not correct for the offline session. Have a look below. 

**Scenario 1 - Offline session with Creator Only Ticked**
1. Create a new session. 
<img width="499" alt="Screenshot 2023-02-08 at 15 08 40" src="https://user-images.githubusercontent.com/104978004/217568918-bfc7aac1-2198-4249-9d85-d5cbc971b459.png">
(The query is quite basic, just getting Features in specific state where complexity is empty/not filled in. Complexity is where we store the outcome of estimation).
<img width="1180" alt="Screenshot 2023-02-08 at 15 09 41" src="https://user-images.githubusercontent.com/104978004/217569304-369c07ba-ed83-4eff-a0ea-f793a929fae8.png">
2. Session is created
<img width="250" alt="Screenshot 2023-02-08 at 15 11 51" src="https://user-images.githubusercontent.com/104978004/217569786-0162fd2b-0b96-4da4-a587-bca6ad454fc6.png">
3. As a creator I open the session and can click on items in it, estimate, save, etc. 
<img width="1169" alt="Screenshot 2023-02-08 at 15 13 04" src="https://user-images.githubusercontent.com/104978004/217570257-7f1a1282-d101-4237-96f4-b1255b63f3b2.png">
As a non creator on the same page I just cannot click on work items to reveal them (no link is available). So I cannot see card details / vote.
This is what caught my eye - I get this response for this session:
<img width="359" alt="Screenshot 2023-02-08 at 15 18 09" src="https://user-images.githubusercontent.com/104978004/217571708-839060e1-6d7e-45bc-99f8-2b2965f4137c.png">
OUTCOME: non creator CANNOT open (click on / link is missing) any work items on the left and cannot vote. It's almost like it's treated as an online session and the creator is the only person who can click and change items on the screen.

**Scenario 2 - Offline session with Creator Only Unticked**
IF I create a similar session with one difference - the creator tickbox - I get:
1. Session:
<img width="480" alt="Screenshot 2023-02-08 at 15 46 13" src="https://user-images.githubusercontent.com/104978004/217579419-70fe42da-7641-4772-887d-d8a901225877.png">
2. Session is created:
<img width="242" alt="Screenshot 2023-02-08 at 15 46 32" src="https://user-images.githubusercontent.com/104978004/217579451-764a9e72-f4cd-4e53-afed-c6cc4e3fa5c5.png">
3. Response:
<img width="400" alt="Screenshot 2023-02-08 at 15 46 51" src="https://user-images.githubusercontent.com/104978004/217579483-da8937e5-4c2f-4a81-8a29-1b3b7d833d66.png">

OUTCOME: non creator can open work items and vote... But they can also save each other votes which creates chaos :) 


I think in the first scenario onlyCreatorCanSwitch should actually be False to allow other team members switch / open items.

**Comment by nataliia-ckb** [comment]
@AminTi hey! Just wondering if you were able to replicate the issue? :)

**Comment by AminTi** [comment]
Hi @nataliia-ckb  I add it to the backlog, for the moment  I have to work on other extensions.  
I will work on it as soon as possible.

**Comment by nataliia-ckb** [comment]
Thank you very much :) Sorry, was only checking as the item is closed so was curious as to whether the info was okay :)

**Comment by AminTi** [comment]
Thank you  @nataliia-ckb  I let you know if I need some logs.

**Comment by nataliia-ckb** [comment]
Hey @AminTi just wanted to ask whether you had a chance to look at this one :)
Sorry, just had another case where one person in a team saved their vote for all the tickets, instead of just voting, so thought I'd ask!

**Comment by AminTi** [comment]
HI! Nataliia I Add it to the backlog (Old Issue).  this person clicked on save for that's why.

**Comment by nataliia-ckb** [comment]
@AminTi oh I'm so sorry, I started testing and got completely overtaken by the work tasks. :( 
I'm really baffled by this, as we're still getting still the same issue.

As you're saying, I would expect that by selecting the "Only the creator can change work items and commit" option my team member would be able to vote, but not save, open links, etc. However, at the moment they cannot vote. 

Using the following settings 
![image](https://github.com/microsoft/azure-boards-estimate/assets/104978004/ea2e3177-791d-4b97-a901-3882df5927cd)

When I am the creator of the session, I get this: 

https://github.com/microsoft/azure-boards-estimate/assets/104978004/02b5f975-2644-4701-8233-6e29eeb237b3

When my colleague created the session with the same setting, shared a link with me and I opened it to vote - I get this: 

https://github.com/microsoft/azure-boards-estimate/assets/104978004/1dd598dc-7ba2-485d-8332-1b65a15f3503

Essentially, I just cannot click into to vote on any of the items. 

I may be I'm doing something wrong, but I really can't see what - we are using just the online version of https://dev.azure.com/ (not on premises etc), got the latest version of the plugin. 

The issue is only visible when one person creates a session and then the other person tries to vote on that session.

**Comment by nataliia-ckb** [comment]
Hey @AminTi just wondered if you got a chance to have a look at the videos above. We've just tested again and the behaviour is still the same - if I create a voting link and select that "only creator can change work items" none of my team members can vote :'( I really don't understand what is happening as we can't be the only ones having this issue.

**Comment by AminTi** [comment]
The person who started the session has to click on the ticket before the other person can vote.

**Comment by nataliia-ckb** [comment]
@AminTi thank you for your response! Could I just check, how it it possible in an offline session? Or do you mean I need to click through all of them before sending the link?

**Comment by AminTi** [comment]
I can check and get back to you.

**Comment by AminTi** [comment]
Hi, @nataliia-ckb We will make an exception for offline sessions, it will be released next week.

**Comment by nataliia-ckb** [comment]
Oh this is incredible, thank you very much!!!! :)

**Comment by AminTi** [comment]
Hi @nataliia-ckb  I just released an update now, It will work for your team now

**Comment by nataliia-ckb** [comment]
@AminTi tested on a few voting rounds now and it works perfectly 🎉 Thank you very very much. 🧁

**Comment by nataliia-ckb** [comment]
Hi @AminTi! The fix worked perfectly until the last release 😭 We are on 2.3.90 and stopped working again - same behaviour as initially described - non creator cannot open and vote on items in offline estimate mode 😭 
Our last round of voting was on 10 Jan 2024, it worked perfectly. Then with the same link the team members were no longer able to vote. Perhaps something added in the last release that messed up the fix?

**Comment by AminTi** [comment]
Hi @nataliia-ckb! I wanted to inform you that the issue has been successfully resolved, and we are scheduled to release the fix on Monday. If you encounter any problems with the extension, please create a new issue for prompt attention.

Thank you for your cooperation and understanding.
