### ISSUE TITLE
Errors when viewing (and ending) Sessions

### ISSUE THREAD

**Issue by Febiunz** [microsoft/azure-boards-estimate#209]
We unfortunately are getting some errors when trying to end some old sessions, that is we don't see any direct errors when clicking on the "End session" link, but the sessions stay visible on the hub. We do get 3 different errors trying to open the 3 different sessions which may help in troubleshooting the issue:

1. Could not load session: 404:
2. Could not load session: Querying folders is not supported.
3. Could not load session: TF401243: The query 18f9d807-e5de-4b17-b755-9e43d01dc155 does not exist, or you do not have permission to read it.

The last error has the most clear response, but I have organization collection admin permissions so that's not the case in this error. If I could be of any assistance in trying to fix these errors let me know.

**Comment by AminTi** [comment]
Hi!  Thanks for reporting.

**Comment by AminTi** [comment]
Hi @Febiunz,  I could not reproduce this issue. If you are still having the same problem let me know so we can book a web session so I can help you.

**Comment by Febiunz** [comment]
Yep, same issue still resists. Not sure how a websession can help, but I am open for it :-)

**Comment by AminTi** [comment]
It works as expected for me.  amin.titi@solidify.dev  I  can now.
