### ISSUE TITLE
Blank screen/work items not loading when clicking on work items in estimation tool

### ISSUE THREAD

**Issue by deanagarrott** [microsoft/azure-boards-estimate#21]
Last week when our team used the estimation tool, we had a blank screen when clicking on 1 work item.
This week, we had to use another method instead of the Estimate tool in DevOps, because every work item we clicked on resulted in a blank screen/the work item not loading whatsoever. We were working in offline mode. Please advise.

**Comment by mcb2001** [comment]
We experience this as well. The problem occours everytime we use the "coffee" vote.

**Comment by MOlausson** [comment]
This is probably the same as #13 and #14. We're look into this now and will release a fix asap.

**Comment by MOlausson** [comment]
We released an update that should resolve this (2.3.1).
