### ISSUE TITLE
Sort sessions by display name

### ISSUE THREAD

**Issue by Cadacious** [microsoft/azure-boards-estimate#215]
Estimate session cards appear to be sorted by session ID (screenshot below) and not display name.

Sorting sessions by display name would greatly assist users in finding specific sessions in a much more predictable fashion.

![image](https://user-images.githubusercontent.com/32421665/216396316-709a7d34-0519-47f0-98e8-e2bc9632bd6c.png)

**Comment by AminTi** [comment]
I will review your pull request as soon as possible.
