### ISSUE TITLE
Estimate extension sticks on "Connecting to server..."

### ISSUE THREAD

**Issue by Cristiana63** [microsoft/azure-boards-estimate#218]
I cannot open old sessions o new cerated ones, neither on prem nor in Azure Cloud: the extension stays on a spinning circle with the message "Connecting to server..."

my colleagues experience the same issue

this is the version of Estimate
![image](https://user-images.githubusercontent.com/125377412/218766565-4eb6dac9-cd9e-48e4-ba74-94634675976c.png)

**Comment by AminTi** [comment]
Thanks for reporting, can you describe your environment?

**Comment by Cristiana63** [comment]
Hi AminTi, thank you for reaching out.
We use the following environments:

About Azure DevOps Server
Version Dev18.M170.6

About Azure DevOps Service
Version Dev19.M216.1 (AzureDevOps_M216_20230206.3)

**Comment by Hodgie** [comment]
My organization is experiencing the same issue. When creating a session explicitly, we remain stuck at the Connecting to server status or are prompted to select a work item on the left with no items available. When trying to Estimate a selected list of work items, we are presented with a blank screen. We are using the cloud Azure DevOps with the latest version of the extension installed. 
![image](https://user-images.githubusercontent.com/730126/220474021-3d6ccf6e-c8b5-45a3-9295-6e7a7ce45b7e.png)

**Comment by AminTi** [comment]
Hi, do you still have the same issue?

**Comment by Hodgie** [comment]
It appears to be working now. Thank you.

brad

**Comment by Cristiana63** [comment]
sorry, still not working for me: do I need to update something?

**Comment by mariejennifer2016** [comment]
We are experiencing the same intermittent issue across our Azure DevOps org.  We have been getting 3-5 complaints/week for the past 3 weeks.  

We have been updating as new versions become available and are currently on version 2.3.83, last updated Mar 4, 2023 at 4:56 PM MST

**Comment by Svashly** [comment]
We have same issue on azure > Boards > Estimate
First you see
`Loading work items..`
then you see
`Connecting to server..`
<img width="1598" alt="image" src="https://github.com/microsoft/azure-boards-estimate/assets/144381973/342198f2-d378-4e0b-be03-c8665e2e64d9">
