### ISSUE TITLE
Estimate session stuck on username/password prompt

### ISSUE THREAD

**Issue by ka-kalee** [microsoft/azure-boards-estimate#225]
Running ADO 2019 and using Active Directory for login authentication. Everytime I try to open an session, it get stuck on prompting username and password.

![signin](https://user-images.githubusercontent.com/108949067/222817749-1078dc48-7595-496d-bdb0-3532a602382c.png)

**Comment by AminTi** [comment]
Hi, do you still have the same issue?

**Comment by ka-kalee** [comment]
Yes I still see the same issue

**Comment by vbtrek** [comment]
We have the same issue. Installed on a self hosted instance of Azure DevOps Server 2019.
Any suggestions?

**Comment by AminTi** [comment]
Hi guys the only solution for the moment is to create an offline session.
