### ISSUE TITLE
Unable to publish extension due to error : - Incompatible API version (5.1)

### ISSUE THREAD

**Issue by jannuvi** [microsoft/azure-boards-estimate#227]
We've just come across the same issue using the latest extension from the marketplace.
#121 
<img width="251" alt="EstimateExt_error" src="https://user-images.githubusercontent.com/101321346/223119680-deb303c8-cb8d-4203-9de6-9c1085b0466b.PNG">

Azure Instance Details:
Azure DevOps Server 2019 (on premise)
Version 17.143.28621.4

**Comment by jannuvi** [comment]
@AminTi - this page seems to suggest the 'supported' API version for 2019 is 5.0 - does this mean the extenstion doesn't work with Azure Devops Server 2019?
https://learn.microsoft.com/en-us/azure/devops/integrate/concepts/rest-api-versioning?view=azure-devops

**Comment by AminTi** [comment]
Hi, it should work for 2019, will check and get back to you

**Comment by jannuvi** [comment]
@AminTi  Any updates on the issue ?

**Comment by AminTi** [comment]
HI! I had to prioritize some other issues, but I will try to reproduce it as soon as possible.

**Comment by abbottbd** [comment]
IMHO it seems pretty simple.  Azure Devops 2019 only supports API version 5.0 - look at the MSFT document in the link here: 
https://learn.microsoft.com/en-us/azure/devops/integrate/concepts/rest-api-versioning?view=azure-devops

The manifest for this extension says 'API vesion 5.1' hence Azure Devops Server 2019 blocks the install (5.1 > 5.0).  Do you actually need anything that exists in API version 5.1 but doesn't exist also in API version 5.0?

**Comment by jannuvi** [comment]
> IMHO it seems pretty simple. Azure Devops 2019 only supports API version 5.0 - look at the MSFT document in the link here: https://learn.microsoft.com/en-us/azure/devops/integrate/concepts/rest-api-versioning?view=azure-devops
> 
> The manifest for this extension says 'API vesion 5.1' hence Azure Devops Server 2019 blocks the install (5.1 > 5.0). Do you actually need anything that exists in API version 5.1 but doesn't exist also in API version 5.0?

@AminTi  any updates on this query ?

**Comment by AminTi** [comment]
Hi, I just released an update now and test it on-prem 2019 it works as expected. let me know if you still have the same issue.
