### ISSUE TITLE
Can't delete old session

### ISSUE THREAD

**Issue by cluen** [microsoft/azure-boards-estimate#229]
We've an old session from before migration vom TFS on premise to Azure that couldn't be ended. If we click on the session a 404 page load error occurs. If we click on context menu "End session" nothing appears in network tab.

Is there any way to end / delete this session?

**Comment by AminTi** [comment]
hanks for reporting, can you describe your environment? Can you see any error in the console or network log in the browser (using F12, debug tools)?

**Comment by cluen** [comment]
Yes there are some failures in console for the landing page of the extension
![grafik](https://user-images.githubusercontent.com/15816331/224311587-8788cc80-78b4-4389-9338-893f04d9155a.png)

The 404 errors are for the url documents:
https://extmgmt.dev.azure.com/XXXXXX/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/estimate/Data/Scopes/Default/Current/Collections/EstimationSessions/Documents

But for the simple click on End session on the problematic Session there is nothing. No network requests or log entries in console.

**Comment by AminTi** [comment]
Hi! do you use VPN?

**Comment by AminTi** [comment]
#258
