### ISSUE TITLE
Is there any way to track the active sessions in the project of the organization or how to track active sessions

### ISSUE THREAD

**Issue by NidhiBuddhiraja** [microsoft/azure-boards-estimate#232]
In my current project, there are lots of active sessions so, first question is is their any default life time associated with these sessions, if yes, then what is that period?
Second is their any way to fetch all the active sessions, sometimes we create the sessions for estimations but we forgot to end that sessions so, that's why that number gets increased and we are trying to find a way to manage this. 

Can you please help me with this query?

**Comment by AminTi** [comment]
hi, there is no way to fetch all the active sessions. which number gets increased?
