### ISSUE TITLE
Unable to load estimating board if the board was created with "Only creator can change work items and commit" = true

### ISSUE THREAD

**Issue by LoriSmi** [microsoft/azure-boards-estimate#234]
This issue has just surfaced.  

**Step 1:** I created an estimating board with these selections:

- Session Title:  added a title
- Mode: Online
- Work Items: Query
- Query: [selected my query]
- Cards: Fibonacci
- Security: toggled on
- Click 'Create'

**Step 2:** Board is created and I return to the Home page.  I normally have to refresh for the new board to appear.  When I refresh, I see a blank white screen with console error (see below).  If I reclick on the "Estimate" option on side bar...I can see all the estimator boards. 
__utils.js:262 uncaught at Gn at Gn 
 at d 
 at Zn 
 TFS.WebApi.Exception: 400: 
    at Object.<anonymous> (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.3.83/1677974050650/build/static/js/1.a5b06016.chunk.js:1:831728)
    at https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.3.83/1677974050650/build/static/js/1.a5b06016.chunk.js:1:830251
    at Object.next (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.3.83/1677974050650/build/static/js/1.a5b06016.chunk.js:1:830356)
    at a (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.3.83/1677974050650/build/static/js/1.a5b06016.chunk.js:1:829101)_

**Step 3:** If I click on the session I just created, it doesn't load. The same blank white page renders instead of the sizing session.

**Comment by LoriSmi** [comment]
Hi,
Yes... I am using Windows 10 Enterprise operating system.  
I tried to access in both Chrome and Firefox:

- Chrome version Version 111.0.5563.65
- Firefox version 111

Thanks for working on this!  Let me know if you need anything else!
Lori

**Comment by AminTi** [comment]
Hi, @LoriSmi we can book a web session so I can help you.

**Comment by LoriSmi** [comment]
Hi, @AminTi I believe my issue has been resolved!  I verified this morning I am able to create and remove a board.  

Thanks!
Lori
