### ISSUE TITLE
0.5 value not taken into account correctly for averages

### ISSUE THREAD

**Issue by hangy** [microsoft/azure-boards-estimate#235]
If votes contain a value of 0.5, the average value is too low.

1. Card values are always parsed as an integer, so that 0.5 is interpreted as 0. https://github.com/microsoft/azure-boards-estimate/blob/c6183a49592fa85a0ff724f8649b5969334fa172/src/pages/session/components/workItemView.tsx#L172-L175
2. Additionally, in the "Default" card set, the value that has the label "0.5" is 0. https://github.com/microsoft/azure-boards-estimate/blob/c6183a49592fa85a0ff724f8649b5969334fa172/src/model/cards.ts#L27-L30

Except for the t-shirt sizes, the values are stored as a Number anyways, so that parsing the value seems redundant. "0.5" having a value of 0 is inconsistent.

**Comment by AminTi** [comment]
Hi Hangy, I saw your Pr I checked it, and I have to merge another Pr before yours. but I will click on reopen.
