### ISSUE TITLE
Work item's description not visible when using the dark mode in Azure DevOps.

### ISSUE THREAD

**Issue by dianapaula19** [microsoft/azure-boards-estimate#238]
When viewing a work item's card, its description isn't visible when using the dark mode. 
I think the reason is that the color of the text stays the same for both the light mode and the dark mode.

**Comment by AminTi** [comment]
Hi!, Thanks for reporting it will be fixed in an upcoming release.

**Comment by AminTi** [comment]
Hi, It works as expected, you have to update the page if you update a description. 
![Screenshot 2023-03-31 at 09 27 01](https://user-images.githubusercontent.com/54841342/229082481-579f1a38-2c82-48bc-a0f6-64d37a1d5e40.png)
