### ISSUE TITLE
Special Characters In Estimating Session Title Causing Errors 

### ISSUE THREAD

**Issue by epetroff1** [microsoft/azure-boards-estimate#249]
We've been having issues getting our estimating sessions up after creating them and getting blank screens. We did a little bit of QA on our side and determined it was the / in the title that was causing errors because our team likes to name our sessions "Team A - 3/4/2023" as an example.

We tested a few more special characters like . or - and those worked perfectly fine.

**Comment by AminTi** [comment]
Thanks for reporting it will be fixed in an upcoming release.
