### ISSUE TITLE
Could not load session: 404: Not Found

### ISSUE THREAD

**Issue by hangy** [microsoft/azure-boards-estimate#25]
### Steps to reproduce

1. On a project that uses the "Agile" process `adcc42ab-9882-485e-a3ed-7678f01f66bc`, create a new estimation session that contains work items.
2. Open the created session.
3. Observe the following error:
![grafik](https://user-images.githubusercontent.com/87124/130438323-03d88652-5dae-4b7b-b15d-1082e7ada420.png)

### Analysis

The error looks to be related to the process type. Apparently, for a project with this new "inheritance" model, the extension requests the workitems from two URLs:

1. https://tfs.example.org/SomeProjectCollection/{SomeGuid}/_apis/wit/workItemTypes
2. https://tfs.example.org/SomeProjectCollection/_apis/work/processes/adcc42ab-9882-485e-a3ed-7678f01f66bc/workItemTypes

The latter call is not present in older (XML?) based process configurations, and 404s in our "agile" project, probably causing the 404 error.

### Additional information

In the [original bug report](https://github.com/cschleiden/azure-boards-estimate/issues/156), it was not clear why this was happening in some collections and not in others. @ray-cuadra and I noticed that [it might be related to project collections that were upgraded from some prior version to Azure DevOps Server 2020](https://github.com/hangy/azure-boards-estimate/issues/28#issuecomment-840379939). I previously [reported this to MS](https://developercommunity.visualstudio.com/t/Work-Item-Types---List-404/1424164?space=22]), but unfortunately, it was closed as "not a bug".

The service is called in the following line: https://github.com/microsoft/azure-boards-estimate/blob/1004739ea32fa6b211aeb82072ca4f8422aa9302/src/services/workItems.ts#L189-L191

### Links to prior issues

- cschleiden/azure-boards-estimate#86
- cschleiden/azure-boards-estimate#156
- hangy/azure-boards-estimate#28
- [Work Item Types - List 404 - Developer Community](https://developercommunity.visualstudio.com/t/Work-Item-Types---List-404/1424164?space=22])

**Comment by MOlausson** [comment]
Thanks @hangy for a great issue report! We'll dig into this now.

**Comment by Robinlievrouw** [comment]
Also having this issue.

**Comment by xymunter** [comment]
Just for the sake of completeness: we're encountering the same problem on Azure DevOps Server 2020 On Premise, but we're using the Hosted-XML templates.

**Comment by Robinlievrouw** [comment]
Any update on this issue? @MOlausson

**Comment by jmilgie** [comment]
We are also having this issue. let us know if there's useful debug information we can help you collect.

**Comment by MOlausson** [comment]
@Robinlievrouw @jmilgie are you also seeing this on xml type processes?

**Comment by Robinlievrouw** [comment]
I'm not sure what you mean by this @MOlausson, could you elaborate?

**Comment by Blackbaud-BlakeMoody** [comment]
We have had this issue and are just trying to delete/end the old session. Doesn't seem to respond to that request when we use the UI to 'End session." The prompt tells us this is going to affect every user in the session and we proceed. But the session is still there.

**Comment by RedGrnBluCat** [comment]
Hello. Our team also has this problem since a week ago. We were doing a quick demo of the group-voting-to-estimate process for another team with online/query/Fibonacci options, and now the session tile is stuck. We cannot enter the session with a 404 error, and it won't end from its drop-down menu item, 'End session.' It also affects other sessions we've created since then - we cannot end other sessions from the Estimate frame, but we can end sessions from within the session.
![image](https://user-images.githubusercontent.com/99514265/154169796-79d9ad86-a9a6-49d1-b17d-3235928a1e3c.png)

**Comment by Robinlievrouw** [comment]
Any update @MOlausson  @AminTi

**Comment by MOlausson** [comment]
> I'm not sure what you mean by this @MOlausson, could you elaborate?

@Robinlievrouw regarding xml processes I was referring to if the environment you are on are use the old process types or the newer ones (which you can configure in the UI)? We're trying to repro but haven't been able to so looking for clues to in when it's happening. If you can describe your scenario and environment could be helpful.

**Comment by Hardrada** [comment]
Having similar issues with this extension. 
![image](https://user-images.githubusercontent.com/2984126/165550107-59621f0a-a658-4d62-9c3f-b29e9eb6a9ac.png)
Websockets fail and the documents list gets a 404. 
This a cloud hosted instance of AZDO.

**Comment by ray-cuadra** [comment]
Would it be possible to get an update on the status of this open issue?

**Comment by Zkanna** [comment]
Good afternoon.

Please tell me who solved this error? Latest version similarly causes errors

**

> {"$id":"1","innerException":null,"message":"%error=\"1660002\";%:The collection does not exist\r\n%error=\"1660002\";%:The collection does not exist","typeName":"Microsoft.VisualStudio.Services.ExtensionManagement.WebApi.DocumentCollectionDoesNotExistException, Microsoft.VisualStudio.Services.ExtensionManagement.WebApi","typeKey":"DocumentCollectionDoesNotExistException","errorCode":0,"eventId":3000}

**


Запросить URL: https://ХХХХХХХХХ/tfs/DefaultCollection/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/estimate/Data/Scopes/Default/Current/Collections/sessions/Documents
Метод запроса: GET
Код статуса: 404 Not Found
Удаленный адрес: ХХ.ХХ.ХХ.ХХХ:443
Правило для URL перехода: strict-origin-when-cross-origin

**Comment by Robinlievrouw** [comment]
This has not been fixed.

> Good afternoon.
> 
> Please tell me who solved this error? Latest version similarly causes errors
> 
> **
> 
> > {"$id":"1","innerException":null,"message":"%error="1660002";%:The collection does not exist\r\n%error="1660002";%:The collection does not exist","typeName":"Microsoft.VisualStudio.Services.ExtensionManagement.WebApi.DocumentCollectionDoesNotExistException, Microsoft.VisualStudio.Services.ExtensionManagement.WebApi","typeKey":"DocumentCollectionDoesNotExistException","errorCode":0,"eventId":3000}
> 
> **
> 
> Запросить URL: [https://ХХХХХХХХХ/tfs/DefaultCollection/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/estimate/Data/Scopes/Default/Current/Collections/sessions/Documents](https://%D0%A5%D0%A5%D0%A5%D0%A5%D0%A5%D0%A5%D0%A5%D0%A5%D0%A5/tfs/DefaultCollection/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/estimate/Data/Scopes/Default/Current/Collections/sessions/Documents) Метод запроса: GET Код статуса: 404 Not Found Удаленный адрес: ХХ.ХХ.ХХ.ХХХ:443 Правило для URL перехода: strict-origin-when-cross-origin

This has not been fixed.

**Comment by AminTi** [comment]
it work as expected for me.

**Comment by funnyDjo** [comment]
Hi @AminTi ,
I recently installed Estimate on our Azure and OnPrem 2020 collections.
This issue is still appearing on the legacy project created with XML template.
It does not happen with the recently created project.

Any hope to release a fix and work with the legacy APIs ?

**Comment by rakeshspyder** [comment]
@AminTi , I'm also facing same issue- Could not load session: 404: Not Found. 
Appreciate if you could help to resolve the issue??

**Comment by thomas-parrish** [comment]
We've been using the tool without issues for over a year with our Azure DevOps Services. We can no longer access sessions, and I get the following console error: 

![image](https://user-images.githubusercontent.com/8125983/225025759-f92aadde-1508-419d-89be-3a57b430e1ba.png)

**Comment by thomas-parrish** [comment]
Any updates here? We still cannot use the plugin. I've removed the extension, re-added it, no effect. Just document not found every time I open any session..

**Comment by epetroff1** [comment]
We've been having this issue for weeks and we might have just figured it out on our side. Team members of mine would create estimate sessions and title them with date such as "Team A 4/3/2023" or "Sprint 4 - 3/17/23" and it was causing the problem. So I would load up a session and call it "April 3rd" or "Blue team - Mar 31st" and it worked. 

We also had previous estimating sessions that were not closed out from before that had the / in them, and we could not open those either. We tested . and - and a few other special characters and determined it was just the / in the title causing problems. 

Hope this helps anyone else out there because that is what's solved our issue!

**Comment by thomas-parrish** [comment]
> We've been having this issue for weeks and we might have just figured it out on our side. Team members of mine would create estimate sessions and title them with date such as "Team A 4/3/2023" or "Sprint 4 - 3/17/23" and it was causing the problem. So I would load up a session and call it "April 3rd" or "Blue team - Mar 31st" and it worked.
> 
> We also had previous estimating sessions that were not closed out from before that had the / in them, and we could not open those either. We tested . and - and a few other special characters and determined it was just the / in the title causing problems.
> 
> Hope this helps anyone else out there because that is what's solved our issue!

I see you opened an issue specifically for this. 

I can confirm that this is the issue causing our inability to load sessions (we had been naming them based on the date.)

**Comment by nslul** [comment]
We have this issue for a year now. and look at the comment above. No one @AminTi seems to be worrying about this. Bad service. So we might as well as look for another solution and delete this extension

**Comment by michvllni** [comment]
As of today, we still encounter this issue on Version Azure DevOps Server 2022.0.1 (AzureDevOpsServer_20230602.5). We're also using the legacy XML Process Model until we manage to migrate to inherited

**Comment by AminTi** [comment]
Hi guys, the issue happens when you deleted the query or when the query is private. I created a reset button, the functionality will remove all sessions.
![Screenshot 2023-08-03 at 11 09 23 (2)](https://github.com/microsoft/azure-boards-estimate/assets/54841342/b5eda9d2-5949-4cf4-a1bd-11d5225c74b8)

**Comment by michvllni** [comment]
@AminTi is there a roadmap or anything where we can see when this goes live? According to the marketplace, the last update was on the 19th of june and I cannot find anything regarding releases neither on github nor on the marketplace

**Comment by AminTi** [comment]
check now

**Comment by michvllni** [comment]
![image](https://github.com/microsoft/azure-boards-estimate/assets/45660891/9402591f-54e9-4a66-bad0-1ae7e0fd54c0)
Still the same

**Comment by AminTi** [comment]
![Screenshot 2023-08-04 at 11 56 26](https://github.com/microsoft/azure-boards-estimate/assets/54841342/44bc49e8-f9fe-43dd-a9e1-e1649e3d70f9)

**Comment by michvllni** [comment]
Oh I think I know the issue. Might it be that you only released this fix for Azure DevOps Services, but not for Azure DevOps Server 2022?

**Comment by AminTi** [comment]
just uninstall and install it again

**Comment by michvllni** [comment]
Thank you that worked. Unfortunately, the issue still persists. When trying to open a session on a query or sprint that still uses the old process model, when trying to open the session I get a 404 with the following error 
![image](https://github.com/microsoft/azure-boards-estimate/assets/45660891/b96ef3ed-5467-43c5-806c-1345c595ff9b)

**Comment by NicolleMayol** [comment]
I'm also still getting this issue. Also working with Azure DevOps Server. This only happens in one of the collections of my environment, the other ones seem to work fine. 

I have three collections in my organization: Two XML based ones (imported from TFS) (lets call them A and B), and one inherited (created anew on Azure DevOps Server) (lets call it C). Collection B and C work fine, but collection A (any project in it) has the issue.

I am already on the latest version, and tried uninstalling and installing again and it still is not working correctly.
