### ISSUE TITLE
Unable to publish extension due to error : - Incompatible API version (5.1)

### ISSUE THREAD

**Issue by jannuvi** [microsoft/azure-boards-estimate#250]
After trying with the latest released version i.e. 2.3.84 we are still facing the same issue.         

Hi, I just released an update now and test it on-prem 2019 it works as expected. let me know if you still have the same issue.

_Originally posted by @AminTi in https://github.com/microsoft/azure-boards-estimate/issues/227#issuecomment-1493007228_
            
<img width="960" alt="estimateerr" src="https://user-images.githubusercontent.com/101321346/230123731-8350b662-c70b-4d18-ae39-cdfd409c1f27.PNG">

**Comment by AminTi** [comment]
Hi @jannuvi we currently support ADO on-prem 2019 first update.
