### ISSUE TITLE
Could Not Load Session errors for certain users

### ISSUE THREAD

**Issue by dennislubins-asc** [microsoft/azure-boards-estimate#251]
Hello,

We recently installed the latest version of the Estimate extension and are having some issues with a few users. Myself and another person can access created sessions, but when a few others try to access them they receive this error...

Could not load session: TF400893: Unable to contact the server. Please check your network connection and try again.

We verified all access matches those that are working. Everything else for Azure boards works fine. Just wondering if you have any ideas of things to check with this.

Thanks

**Comment by AminTi** [comment]
HI! Do you know if they use VPN?

**Comment by DennisL011116** [comment]
Yes, all 3 users are on 3 different VPN's spread across the US. My self and the working user also are on 2 of the same VPN's as the users that are affected.

**Comment by AminTi** [comment]
Can you describe your environment? Can you see any error in the console or network log in the browser (using F12, debug tools)?

**Comment by DennisL011116** [comment]
[tfs.ascensus.com-1682000083169.log](https://github.com/microsoft/azure-boards-estimate/files/11287153/tfs.ascensus.com-1682000083169.log)

Sorry for the late reply, attached is the console log from one of the users.

**Comment by DennisL011116** [comment]
@AminTi - Any update on this?

**Comment by dennislubins-asc** [comment]
@AminTi  - Just checking on this

**Comment by AminTi** [comment]
Hi @dennislubins-asc  I believe the issue occurs when the query is private or when you create a query session and then delete the query. We will release a reset button to address this problem.  #25
