### ISSUE TITLE
Estimate Extension Not Loading for Multiple Users

### ISSUE THREAD

**Issue by BenSteele11** [microsoft/azure-boards-estimate#256]
The users get to Connecting to Server, but the extension never loads.  It works for some users.

**Comment by AminTi** [comment]
Thanks for reporting, can you describe your environment? Can you see any error in the console or network log in the browser (using F12, debug tools)?

**Comment by BenSteele11** [comment]
No error, but the following backend request is stalling out: Request URL:

https://msdevlabs-estimate-backend.azurewebsites.net//estimate/negotiate?sessionId=migs8&tfId=607c8ca9-e101-6d91-b83f-fb7942a8e05d

**Comment by BenSteele11** [comment]
An employee tried to ping that url directly, and it looks like they can't reach it from my VM
![MicrosoftTeams-image](https://user-images.githubusercontent.com/131809789/234619350-a3050ad2-894a-48da-87d0-cd2d1adaea23.png)

**Comment by AminTi** [comment]
Do you utilize VPN?

**Comment by BenSteele11** [comment]
Some of our contractors have to stay connected to VPN and cannot disconnect.

**Comment by MOlausson** [comment]
As described in #257 we currently need Estimate to be able to connect to the public endpoint in order to process notifications (voting). If your clients cannot connect then currently the option is to use the offline mode.
