### ISSUE TITLE
ADO Slows down when using azure-boards-estimate

### ISSUE THREAD

**Issue by TeunissenHarry** [microsoft/azure-boards-estimate#259]
When we use this extension in our organization, the sessions slow down to a point that users start to refresh, log in-and-out and complain about the speed. Is this a common perception? Maybe there are some best-practices you can advise? The size of the estiation-pools or the number of users that join the specific estimate?

**Comment by AminTi** [comment]
I have never experienced it, it should work without any problems.

**Comment by AminTi** [comment]
Hi, yes create an offline session.
