### ISSUE TITLE
Team Unable to Open PBIs to Estimate

### ISSUE THREAD

**Issue by neech21** [microsoft/azure-boards-estimate#26]
We created an asynch estimation session. The team could open the session, see the Product Backlog Items but could not click on them to open them and do estimation. Any ideas?

**Comment by hangy** [comment]
Did you check "Only creator can change work items and commit" when you created the session? In that case, only the creator can select the current PBI.

**Comment by neech21** [comment]
We did not select the "Only creator can change work items and commit" option.

**Comment by MOlausson** [comment]
@neech21 did you get this to work?

**Comment by MOlausson** [comment]
@neech21 thanks for confirming. I'll close the issue for now but just reopen if you hit the same problem again.
