### ISSUE TITLE
[BUG] Estimated task is rolled back when moving to the next card

### ISSUE THREAD

**Issue by CatKinKitKat** [microsoft/azure-boards-estimate#261]
When I estimate a task using the Planning Poker for Azure app and move to the next card without refreshing the page, the app jumps back to the previous card and shows no estimate done. However, when I refresh the page, I can see that the estimate has been rolled back.

#### Steps to reproduce:

- Open the Planning Poker for Azure app.
- Select a task to estimate.
- Choose an estimate for the task.
- Move to the next card without refreshing the page.
- Notice that the app jumps back to the previous card and shows no estimate done.
- Refresh the page and observe that the estimate has been rolled back.

#### Expected behavior:

After I estimate a task and move to the next card, the app should save my estimate and move on to the next card without any issues.

#### Actual behavior:

The app jumps back to the previous card and shows no estimate done, and the estimate is rolled back when the page is refreshed.

#### Environment:

**Browser**: Edge 114.0.1823.67 (Official build) (64-bit)
**OS**: Windows 11 Education 22H2 (So sue me, I'm always a student!)

Please let me know if you need any further information.

**Comment by AminTi** [comment]
Thanks for reporting, it will be fixed in an upcoming release.

**Comment by AminTi** [comment]
Upon attempting to reproduce the issues, I can confirm that everything is working as expected. This repo belong to the first extension.
![Screenshot 2023-08-02 at 14 27 28](https://github.com/microsoft/azure-boards-estimate/assets/54841342/4476b59e-4317-4d0b-bf95-f9a87404420e)
 If the issue persists, kindly get in touch with me to arrange a web session for further assistance.
