### ISSUE TITLE
We can't manage custom cards

### ISSUE THREAD

**Issue by anielcrz** [microsoft/azure-boards-estimate#27]
We created a set of custom cards, but it was not possible to edit the card values ​​afterwards.

**Comment by MOlausson** [comment]
@anielcrz can you explain you scenario a bit more? What type of customizations did you do, what worked and what didn't?

**Comment by MOlausson** [comment]
@anielcrz Closing due to lack of response. Feel free to reopen.

**Comment by metri** [comment]
@MOlausson castom card like this https://marketplace.visualstudio.com/items?itemName=EstimationPoker.estimate (card size and card value)
