### ISSUE TITLE
How to restore/restart the ended sessions of the Estimate Tool is Azure Devops?

### ISSUE THREAD

**Issue by sneha5388** [microsoft/azure-boards-estimate#272]
Please add an option to restore the completed / reset sessions of the Estimate Tool.
Or at least create a backup before getting removed.

**Comment by AminTi** [comment]
Hello, once it's removed, restoration is not possible. This issue can occur, for instance, when a user creates a session with a query and then deletes that query. Therefore, please ensure not to delete the query you are actively using.
