### ISSUE TITLE
Add logging to Estimate Sessions Extension to query on using Log Analytics Workspace in case of Unexpected Actions on Estimation Sessions like DELETE

### ISSUE THREAD

**Issue by HassanFad** [microsoft/azure-boards-estimate#275]
Hi Team,

Thanks for making Estimation Sessions available as Extension. We really looking forward to get this as pat of ADO system itself for more logging information to query on using KUSTO query language.
Can you please in the meantime add some logging to this Extension in order to be able to have more logging info to query on in case of unexected actions on this Estimate Sessions like DELETED Sessions or other actions?

This is because we are facing an issue that our previous created Estimate Sessions were deleted and none knows why? and by whom?
In case of more info on this request and having context on this issue, please feel free to reach out to me by email: [fadilieh@delagelanden.com](mailto:fadilieh@delagelanden.com) to set u a call and walk you through the issue

In addition to this request, we have observed that this Estimate Session Extension also has been updated on August 4th, 2023 as mentioned on this page "https://marketplace.visualstudio.com/items?itemName=ms-devlabs.estimate&targetId=74ce0c5c-f819-479e-97c9-75f6ea0b8110&utm_source=vstsproduct&utm_medium=ExtHubManageList". Is that a known issue? Could that be the reason of deletion of our previous Estimated Sessions as far as you may know? Our previous sessions are deleted between 4th and 7th august 2023 and the actual onces are created starting by August 7th, 2023.

Again, for more informtion and follow up, please do reach out to me by the following email fadilieh@delagelanden.com

Thanks in advance.

**Comment by AminTi** [comment]
Hi, thanks for your suggestion.

**Comment by HassanFad** [comment]
Hi [AminTi],

As a follow up on my post above, is there some update on the deleted Estimation sessions on our org at the same time this Extension gets updated? Thanks in advance.

**Comment by TAO-88** [comment]
We also were surprised by all Estimate boards being deleted more than once. With 800 people working in the project we lost a lot of estimate boards. It looks like it is due to the new 'Reset' Functionality. It deleted ALL boards instead of just the one board that needs to be reset. Can you please fix this in order to make the 'reset' only for the selected board and not all estimate boards?

**Comment by HassanFad** [comment]
Thanks [TAO-88] for the confirmation.
[AminTi], what will be the next step to take here to get the Estimation sessions deleted back to AzDo Projects? 

Thanks in advance.

Hassan Fadili

**Comment by MOlausson** [comment]
Hi @HassanFad , thanks for the feedback. Regarding the question about logging - we are unable to provide a solution for this due to a decision to not log anything in respect to data security.

**Comment by HassanFad** [comment]
Hi @MOlausson, Thanks for the reply. Ok, in that case can the deleted estimation sessions be restored? And at least when the extension is updated that this will not delete the available sessions again? 
Thanks.
Best Regards,
Hassan Fadili

**Comment by AminTi** [comment]
Hi!, @HassanFad,  If you choose to reset, all sessions will be cleared. I will include an option that allows only the creator to initiate the reset.

**Comment by TAO-88** [comment]
@AminTi can you please make it so that ONLY the session that is SELECTED to be cleared is cleared? Because it can happen that as a creator you have multiple sessions but you do not want them all to be deleted.

Current 'Reset' is deleting ALL sessions in the project which is a nightmare working with multiple teams and much more than only one session in the project. We already had a few times this months that all our 30+ sessions have been cleared because someone used the Reset button with the impression it would only clear the selected session and not all 30+ sessions

**Comment by HassanFad** [comment]
Hi,

Thanks @AminTi<https://github.com/AminTi> for the reply and the suggestion. In that case I really second the option mentioned by @TAO-88 that ONLY the session that is SELECTED to be cleared is cleared? for the same reason. Can you please implement it that way?

Thanks in advance.

Best Regards,

Hassan Fadili
System Team ADO Engineer at DLL

________________________________
Van: TAO-88 ***@***.***>
Verzonden: maandag 9 oktober 2023 15:14
Aan: microsoft/azure-boards-estimate ***@***.***>
CC: HassanFad ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [microsoft/azure-boards-estimate] Add logging to Estimate Sessions Extension to query on using Log Analytics Workspace in case of Unexpected Actions on Estimation Sessions like DELETE (Issue #275)


@AminTi<https://github.com/AminTi> can you please make it so that ONLY the session that is SELECTED to be cleared is cleared? Because it can happen that as a creator you have multiple sessions but you do not want them all to be deleted.

Current 'Reset' is deleting ALL sessions in the project which is a nightmare working with multiple teams and much more than only one session in the project. We already had a few times this months that all our 30+ sessions have been cleared because someone used the Reset button with the impression it would only clear the selected session and not all 30+ sessions
