### ISSUE TITLE
When we try to open session credentials window is prompting.

### ISSUE THREAD

**Issue by AMARAVATHIVSRKPRASAD** [microsoft/azure-boards-estimate#277]
When we try to open session credentials windows is prompting and it is not accepting the credentials.

Azure DevOps Version: On Prem Azure DevOps Server 2019 Update 1.1.
![image](https://github.com/microsoft/azure-boards-estimate/assets/112699369/b73b94e7-6705-4990-beb6-eab6e6a587b6)

**Comment by AminTi** [comment]
Hello, it seems there might be an issue with your environment. Are you using a VPN?

**Comment by AMARAVATHIVSRKPRASAD** [comment]
> Hello, it seems there might be an issue with your environment. Are you using a VPN?

Yes we are using vpn. Application is hosted in secure vlan.

**Comment by AminTi** [comment]
Turn off the VPN and test it. I have tested it in all our environments, and it has worked fine. If it doesn't work, we can schedule a web session.

**Comment by AMARAVATHIVSRKPRASAD** [comment]
We tried with office network as well. It is the same.
