### ISSUE TITLE
Estimate plug-in has stopped working - endlessly "Connecting to server..."

### ISSUE THREAD

**Issue by EQDGL** [microsoft/azure-boards-estimate#278]
Today the Estimate plug-in (2.3.86) has stopped working on our Azure DevOps Server 2020. Was working OK last week but now you get a "Connecting to server..." page when trying to start a new session. It never connects and does not seem to time out.

One other user has reported this on the Marketplace today so wondering if this is a problem with the plug-in rather then my server instance?

**Comment by AminTi** [comment]
thanks for reporting, Could you help us track this down by checking the browser network log (f12 in the browser), and the console log for errors? There should be an error telling us which api that's failing for you.

**Comment by jochenjonc** [comment]
I also have it and this is what I can see in the console:
![image](https://github.com/microsoft/azure-boards-estimate/assets/436379/f5c56c61-f9f3-4458-9921-3239c5a11a8b)

**Comment by EQDGL** [comment]
Yes, I also see a CORS error

<img width="599" alt="image" src="https://github.com/microsoft/azure-boards-estimate/assets/46818464/a15b7f7c-b2a5-482e-87f0-ccd6cecd3b21">

**Comment by JonJoyce** [comment]
+1

![image](https://github.com/microsoft/azure-boards-estimate/assets/448438/86fccf0c-e9ad-456d-a5f2-6d2be296e7f9)

**Comment by AminTi** [comment]
The issue should have been resolved now, Let us know if you still have problems after refreshing the browser.
