### ISSUE TITLE
Query can't be used if work items have estimating field with "" value

### ISSUE THREAD

**Issue by JBerns-Vcare** [microsoft/azure-boards-estimate#281]
We use the Story Points field as estimating field, so if we estimate and save the result it will be put into this field. This field can be "" aka null, because we use the 0 for Just Do It items. But if I use this query the following error is shown:
![image](https://github.com/microsoft/azure-boards-estimate/assets/132936715/7fa85a66-2665-4e02-a5d1-f0fb77531b9b)

If I use this same query and edit it, so there will be no items without a value, it works. But we use the null value because we need to know which items we haven't estimated yet. 

Is this intended or is this a bug? We would like to use items without a value.

**Comment by AminTi** [comment]
Hello, it seems that the query contained a work item that has been deleted, causing the issue. To resolve this, please reset the extension and ensure that all required work items exist. This should allow the extension to work properly again.
