### ISSUE TITLE
Existing sessions are no longer available.

### ISSUE THREAD

**Issue by NinoCapo** [microsoft/azure-boards-estimate#282]
After services were restored a few weeks back, all of our existing sessions were deleted.  We have since then manually recreated many of our sessions but they are being deleted or are not visible after a few days.

- Were are using Azure DevOps Services with version 2.3.87 (Latest) of this extension.  
- Our project has approximately 40 teams with over 400 users.  
- I am a PCA in the organization.

Please let me know if there is any additional information that I can provide.

**Comment by AminTi** [comment]
Hello, it appears that someone on your team may have reset the extension.

**Comment by NinoCapo** [comment]
@AminTi , I'm not sure I understand your response, can you please elaborate?  We keep recreating sessions and they continually disappear.

**Comment by Faroreness** [comment]
Hello, we are experiencing the same thing. There is no logging within ADO that I can see, and while we only have a handful of teams experiencing this issue, in the last week and a half we've had numerous people come to us and saying that within an hour of creating their sessions, they are disappearing. I cannot troubleshoot; is there any way we can see why/how they're disappearing automatically?

**Comment by AminTi** [comment]
Hi guys, Would you like to schedule a web session so I can help you?
