### ISSUE TITLE
Sessions seem to disappear/delete automatically

### ISSUE THREAD

**Issue by Faroreness** [microsoft/azure-boards-estimate#283]
Hello, we have some teams in our org using this extension and in the last week and a half they are all reporting their sessions are getting deleted, but no rhyme or reason as to why. I cannot troubleshoot in any way within ADO; there is no logging attached to this extension and I cannot see any history related to their sessions or help advise on a solution (if appropriate).

I don't know what other next steps to take to troubleshoot, can someone help advise on what actions I might be able to take?

**Comment by AminTi** [comment]
Hi!, a session can be deleted if someone resets the extension.

**Comment by Faroreness** [comment]
Hello - can you help advise how extensions are generally reset? I am an admin in my ADO workspaces and don't seem to have a general 'reset' option from the extension main page. I only see options to disable and uninstall the extension or view its details on the marketplace.

We haven't changed any internal process(es) that I know of that would automate a reset of the extension either.

**Comment by AminTi** [comment]
![Screenshot 2023-08-03 at 11 19 07](https://github.com/microsoft/azure-boards-estimate/assets/54841342/1ffcf3ed-556a-456f-8d87-7dbb 
If you choose to reset, all sessions will be cleared.

**Comment by AminTi** [comment]
![Screenshot 2023-08-03 at 11 19 07](https://github.com/microsoft/azure-boards-estimate/assets/54841342/d99ed198-9ce3-4b04-a78b-1513560b1f97)

**Comment by AminTi** [comment]
If you choose to reset, all sessions will be cleared.

**Comment by Faroreness** [comment]
Ah, I see it's session-specific. Yes, I think the option for creator-only would help us greatly! Thanks so much.

**Comment by AminTi** [comment]
Certainly, it will be available for release next week.
