### ISSUE TITLE
Estimate Planning Poker Tool Access Issues

### ISSUE THREAD

**Issue by fperryus** [microsoft/azure-boards-estimate#287]
Is there a limit to the number of participant users that can log in and participate in a Estimate planning poker session? We are noticing that some team members (team size is 15) each estimating session can't either access from the link or when trying to access directly from the ADO menu (the users that cannot access are not consistent).
Please confirm

**Comment by AminTi** [comment]
I believe there is no limit to how many users can use the extension. if you need help we can schedule a web session amin.titi@solidify.dev
