### ISSUE TITLE
Unable to Join/Start a session

### ISSUE THREAD

**Issue by jmilgie** [microsoft/azure-boards-estimate#288]
We're having issues loading sessions on Azure Devops Server 2022.0.1
![image](https://github.com/microsoft/azure-boards-estimate/assets/14044347/7c2d3747-0da0-4c57-a954-a69e0a994688)
![image](https://github.com/microsoft/azure-boards-estimate/assets/14044347/24fde2a6-2bde-4005-9c6e-665d559b76c0)

with the error:
`
{$id: "1", innerException: null,…}
$id
: 
"1"
errorCode
: 
0
eventId
: 
3000
innerException
: 
null
message
: 
"%error=\"1660002\";%:The collection does not exist\r\n%error=\"1660002\";%:The collection does not exist"
typeKey
: 
"DocumentCollectionDoesNotExistException"
typeName
: 
"Microsoft.VisualStudio.Services.ExtensionManagement.WebApi.DocumentCollectionDoesNotExistException, Microsoft.VisualStudio.Services.ExtensionManagement.WebApi"`

The one documents response that does work responds with this (not sure if this is helpful/relevant)
![image](https://github.com/microsoft/azure-boards-estimate/assets/14044347/7c5b9be1-30d1-4f2d-adf9-2c2a0673774f)

Please let me know if there's other/better information which might be helpful in diagnosing this issue. Our collection has a space in the name, and that's caused us pain in the past - not sure if that's relevant here (ex: 'Collection Name').

**Comment by jmilgie** [comment]
Heya @AminTi I attempted to create more sessions in our collection, but they all have the same issue. I've noticed that when I create sessions in a collection without a space in the name, they work as expected. The only difference I can see is that i'm installing the extention into that collection fresh, whereas in the collection where i'm facing the issue the extension has been installed for some time. Is it possible i'm dealing with remnants of an older installation? 

For what it's worth I did attempt to remove and re-install as well, but to no avail. Wondering if there's a more forceful way to ensure it's fully removed such that it can't re-use cached files if re-installed.

**Comment by AminTi** [comment]
Hi @jmilgie,  you don't have to remove the extension just rest the sessions 
<img width="853" alt="Screenshot 2023-08-03 at 11 05 10" src="https://github.com/microsoft/azure-boards-estimate/assets/54841342/c9ca4026-e799-4e36-afc3-294ef810e0e7">

**Comment by jmilgie** [comment]
Hi AminTi, 

Yes doing this does not solve the problem. This is why I was wondering if older cached versions of this extension are remnant somewhere I can purge. The issue remains.
