### ISSUE TITLE
Connecting to Server just spins and is hanging.

### ISSUE THREAD

**Issue by gjvanetten-pwc** [microsoft/azure-boards-estimate#289]
Hello, we are having this issue for awhile now. When we click on a session it just says connecting to server and spins. I put the link url in the browser and get the following error:

<Error>
<Code>ResourceNotFound</Code>
<Message>The specified resource does not exist. RequestId:c0dc63c0-b01e-00b9-38ff-0028c7000000 Time:2023-10-17T13:42:20.5885070Z</Message>
</Error>
https://ms-devlabs.gallerycdn.vsassets.io/session/&&&&&/&&&&&&&&&& blocking the session info

**Comment by AminTi** [comment]
HI, are you available for a web session?"

**Comment by danisusb** [comment]
I've the same problem... Therefore I could show you the issue..

**Comment by AminTi** [comment]
It works as it should for me, couldn't recreate it.
