### ISSUE TITLE
Stuck at "Connecting to server"

### ISSUE THREAD

**Issue by JohnKlein-Genova** [microsoft/azure-boards-estimate#301]
Looks like this was an issue before and saw responses this was fixed. But currently can't connect to the session. 

![image](https://github.com/microsoft/azure-boards-estimate/assets/98430983/61f6c747-d713-46ff-b8f1-d3e079cce9fc)

What can I do to troubleshoot?  The offline sessions seem to work.

**Comment by AminTi** [comment]
Hello, are you still experiencing the same problems?

**Comment by AminTi** [comment]
let me know if  still experiencing the same problems?
