### ISSUE TITLE
0.5 estimate is treated as 0 in the Average

### ISSUE THREAD

**Issue by SzaboVlad** [microsoft/azure-boards-estimate#310]
As the title says, when we estimate using the default cards (which have 0.5 estimate) and people vote 0.5, that vote is treated as 0 when computing the average.

![image](https://github.com/microsoft/azure-boards-estimate/assets/48243507/1f83efaa-c355-431a-ba6d-6ffcf282b9ed)

Looking at the code, I believe this comes from workItemView.tsx on line 173 when computing the sum used in the average, as it uses parseInt which will force 0.5 to be 0.

```
sum += parseInt(
    card!.value!.toString() ||
    "0"
);
```

**Comment by AminTi** [comment]
Thank you for bringing this issue to our attention, it will be addressed and resolved in an upcoming update.
