### ISSUE TITLE
Boards/estimate module does not load - endlessly "Connecting to server..."

### ISSUE THREAD

**Issue by jpurrTTC** [microsoft/azure-boards-estimate#315]
We are just using dev.azure.com/<orgname>. While trying to access the boards/estimate module it just shows spinning circle that says 'Connecting to server'. This works sporadically but mostly does not load. Please advise.

**Comment by MOlausson** [comment]
@jpurrTTC no this is the right place. Please add to #309, we are looking into this so additional context is helpful.
