### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by CraigRGordon** [microsoft/azure-boards-estimate#316]
I have some users that can not create in the estimate board.  I did however see that there is an issue with the creation on my account being an admin.  I had to put in a Title before anything else, if I didnt I would have to close the dialog and try again.   

The issue my user has is following the title creation first the next two dropdowns are grayed out. ( Team Field and Sprint Field) and because there blank the create button is grayed out.  

The screen shot if from my user account
![image](https://github.com/microsoft/azure-boards-estimate/assets/81634573/04e146bf-9b7f-4531-a2a6-73cb87d56e12)

This is what the user sees:
![image](https://github.com/microsoft/azure-boards-estimate/assets/81634573/6083e1be-a412-4287-81d2-321a571d6548)

**Comment by AminTi** [comment]
Thank you for informing us about this issue. We will investigate it promptly and make the necessary corrections as soon as possible.

**Comment by CraigRGordon** [comment]
is there a permission I need to apply, that would cause this.  it just looks like the users needs something added to there account?  We try to lock down everything is why I'm asking.  If there is something to adjust here let me know.

**Comment by AminTi** [comment]
I will first check the issues to see if they work as expected for me. If they do, we can schedule a web session so that I can assist you further.

**Comment by AminTi** [comment]
I performed a test and checked the code to ensure that nothing was preventing the user from creating a session. I tested it, and it worked as expected. 
Could you help us track this down by checking the browser network log (f12 in the browser), and the console log for errors?

**Comment by AminTi** [comment]
Could you help us track this down by checking the browser network log (f12 in the browser), and the console log for errors?

**Comment by AminTi** [comment]
We will close this issue. If you encounter the same problem again, please feel free to create a new issue
