### ISSUE TITLE
Acceptance Criteria in Preview

### ISSUE THREAD

**Issue by danielhirschi83** [microsoft/azure-boards-estimate#32]
Currently, only the description of the user story is displayed in the preview. Would it also be possible to display the acceptance criteria?
Only this gives the complete scope of the story

**Comment by MOlausson** [comment]
@danielhirschi83 Agree, this would be a nice feature. Adding to the backlog.

**Comment by BeefCake5555** [comment]
@MOlausson we would be very happy to have this feature as well for estimation. Do you know approximately when it could be implemented?
