### ISSUE TITLE
Implement secure connection to MongoDB in Azure DevOps extension

### ISSUE THREAD

**Issue by codigorandom** [microsoft/azure-boards-estimate#325]
We need to implement a secure way to connect to MongoDB from our Azure DevOps extension. The extension adds a custom tab to work items where users can fill in some fields, and this information needs to be stored in MongoDB. Currently, we are facing challenges in obtaining the credentials securely for the MongoDB connection. Could you help me please? tranks

**Comment by AminTi** [comment]
Thank you for reaching out with your query. We understand the importance of securing your MongoDB connection from an Azure DevOps extension. However, we are unable to provide assistance with this particular issue at the moment.
