### ISSUE TITLE
Sessions are sometimes pulling some of the child work items of some other work items, regardless of which iteration path they are in.

### ISSUE THREAD

**Issue by jessicadcrl** [microsoft/azure-boards-estimate#333]
Our sessions are pulling in work items from random iteration paths not specified in the session configuration. It APPEARS that they are child items of work items that were pulled into the session, but not all of them.

**Comment by AminTi** [comment]
Hi, if child items being in the same iteration as their parent items can lead to their inclusion in a session. However, it is not possible for the extension to pull in work items randomly.
