### ISSUE TITLE
User is not able to see the workitem content to estimate in the created session

### ISSUE THREAD

**Issue by Hitaishi2** [microsoft/azure-boards-estimate#337]
After session creation, user is facing issue to view the workitem(user story) details in main pane to estimate the story points. It is impacting the sprint planning. Sometimes it loads but take time of 2-3 mins for one click .
Please prioritize and do the needful.
![image (12)](https://github.com/user-attachments/assets/57be5791-17eb-4db7-ab25-cb467b898f6c)

**Comment by Hitaishi2** [comment]
Hi Team,

Any update?

**Comment by AminTi** [comment]
HI, I was unable to reproduce the issues you're encountering. Could you please check if there are any relevant errors or warnings in the console log or network log? This information could help identify the problem

**Comment by Hitaishi2** [comment]
will check and share you the network logs

**Comment by AminTi** [comment]
Hi, if you're still experiencing the issue, please share the console and network logs with us so we can assist you in the best way possible
