### ISSUE TITLE
Add possibility to group participants

### ISSUE THREAD

**Issue by MikDal002** [microsoft/azure-boards-estimate#338]
Hello! 
It would be very useful to allow user to assign their selves to a specific group. It will later show the average for each group separately (e.g. Developers, Automation Testers, Manual Testers). I attach a possible outcome made in Paint :D.

So, my proposals for simplified acceptance criteria are:

1. When creating a session, User have to click a switch to enable _groups_ which will be available during the session.
  a. At this moment, user can edit a list, where it can add allowed _Groups_ in a session.
2. When user is logging into session with enabled _Groups_ have to select its group in popup window.

![image](https://github.com/user-attachments/assets/38d31f02-6d44-4cfa-a138-a00bc5e8efef)

I can help with Pull Request :).

**Comment by AminTi** [comment]
Hello!, Thank you for the detailed proposal and the example—it helps visualize the feature clearly. I will discuss this idea with the team and get back to you with their feedback.

We appreciate your input!
