### ISSUE TITLE
Votes disappear in the voting process

### ISSUE THREAD

**Issue by AndriyKysiliuk** [microsoft/azure-boards-estimate#339]
Hi, my team found the issue when votes disappear in the voting process and we found the STR:
The precondition is to have 2-3 work items to estimate.

STR:

- The team starts voting for the first work item
- Someone from the team clicks on another work item

**Expected result**: the team still sees the result of voting for the first item
**Actual result**: all votes disappear and the team needs to start voting again

**Comment by AminTi** [comment]
Hi, thank you for reporting this issue. We will test it and get back to you as soon as possible.

**Comment by AminTi** [comment]
We just tested it, and it works as expected. Maybe you should toggle on the 'Only creator can change work items and commit' option.
