### ISSUE TITLE
Cannot save estimate, no field is configured for work items of type Task

### ISSUE THREAD

**Issue by front1989** [microsoft/azure-boards-estimate#34]
The save for the estimation is not working.

The endpoint
_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/estimate/Data/Scopes/Default/Current/Collections/$settings/Documents/4beb812e-dd99-44ee-9aef-b1b687944ae5-field-configuration

The error
{"$id":"1","innerException":null,"message":"%error=\"1660002\";%:The collection does not exist\r\n%error=\"1660002\";%:The collection does not exist","typeName":"Microsoft.VisualStudio.Services.ExtensionManagement.WebApi.DocumentCollectionDoesNotExistException, Microsoft.VisualStudio.Services.ExtensionManagement.WebApi","typeKey":"DocumentCollectionDoesNotExistException","errorCode":0,"eventId":3000}

Could you take a look on that?

**Comment by MOlausson** [comment]
@front1989 Thanks for reporting. Can you explain your scenario in a little more detail? Also are you using Azure DevOps cloud or server?

**Comment by front1989** [comment]
@MOlausson It is on Azure DevOps cloud.

1. This error just happens when i am doing the poker planning for tasks
2. This work for the user stories

If you need anything more, just let me know

**Comment by MOlausson** [comment]
I think the error you see is not related to this. Have you configured the field to use for the Task work item type in the Settings for Estimate?

![image](https://user-images.githubusercontent.com/7904771/134566793-17825da3-0b58-4772-b3ee-2ef2f188d95c.png)

**Comment by front1989** [comment]
@MOlausson thanks  now it is working. I did not find this example on the documentation.

**Comment by MOlausson** [comment]
Great, happy to hear. And I'll add a note to add something about this to the documentation.

**Comment by raphaelmoreira** [comment]
It would be interesting to put this in the [documentation on the extension page](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.estimate).

I had the same doubt here.
