### ISSUE TITLE
Unable to open created sessions

### ISSUE THREAD

**Issue by Abe-Froman** [microsoft/azure-boards-estimate#35]
I think this first started 2 or 3 sprints (4 or 6 weeks) ago and persisted during today's planning...

After creating a session (query based in case it matters) and trying to open it, we're seeing a perpetual "Connecting to server" message while several API calls have failed with 404 errors:

- https://extmgmt.dev.azure.com/{org}/_apis/ExtensionManagement/InstalledExtensions/MS-Device-Engineering-Services/estimate/Data/Scopes/Default/Current/Collections/sessions/Documents
- https://estimate-backend.azurewebsites.net//estimate/negotiate?sessionId={sessionId}&tfId={some-guid}
- https://extmgmt.dev.azure.com/{org}/_apis/ExtensionManagement/InstalledExtensions/MS-Device-Engineering-Services/estimate/Data/Scopes/Default/Current/Collections/%24settings/Documents/{some-guid}-field-configuration

And finally, the following call fails with ERR_NAME_NOT_RESOLVED
- https://estimate-backend.azurewebsites.net//estimate/negotiate?sessionId={sessionId}&tfId={some-guid}

I'm afraid I probably don't have the means to setup a repro but am happy to connect with anyone on the development team through Teams or email.

**Comment by hangy** [comment]
> And finally, the following call fails with ERR_NAME_NOT_RESOLVED
> 
>     * [https://estimate-backend.azurewebsites.net//estimate/negotiate?sessionId={sessionId}&tfId={some-guid}](https://estimate-backend.azurewebsites.net//estimate/negotiate?sessionId=%7BsessionId%7D&tfId=%7Bsome-guid%7D)

You may need to update the extension. Since a few weeks ago, it uses a different backend, because the old one had been shut down. https://github.com/microsoft/azure-boards-estimate/blob/f003afbcdef5f25242743b95d9296854d47cc656/src/services/channels/signalr.ts#L9

**Comment by Abe-Froman** [comment]
We are using the latest version already, I think these are updated automatically:

Installed version:
![image](https://user-images.githubusercontent.com/18315896/134089665-c6adfc2f-ebd2-4356-8374-87cb774e7084.png)

Extension on Marketplace:

![image](https://user-images.githubusercontent.com/18315896/134089694-359933e4-60c9-43b3-8b09-804ae17b24cc.png)

**Comment by Abe-Froman** [comment]
Aaaand as soon as I posted that I realized we probably have the wrong version installed.

I'll see if I can get the admins to install the DevLabs version (2.3.1). I'm not even sure how we got the wrong one installed.

**Comment by hangy** [comment]
> I'll see if I can get the admins to install the DevLabs version (2.3.1). I'm not even sure how we got the wrong one installed.

> ![image](https://user-images.githubusercontent.com/18315896/134089694-359933e4-60c9-43b3-8b09-804ae17b24cc.png)

To me, that looks like an internal preview version. 🙂
