### ISSUE TITLE
Workitem link targets a wrong base address with on-premise configuration

### ISSUE THREAD

**Issue by olivierhelin** [microsoft/azure-boards-estimate#37]
Hello,

We installed the extension on our on-premise ADO Server. When we select a workitem, the link to the open it targets "dev.azure.com" instead of "mycompany.com".

![session](https://user-images.githubusercontent.com/32240757/135051655-8d4d62cf-d31f-4fec-82e4-005067e8041f.jpg)

Please note we get the issue only when we are trying to open it in a new tab (tested on Edge and Chrome)

**Comment by MOlausson** [comment]
@olivierhelin Thanks for reporting, we have some improvements coming in the next release which I hope will address this as well. Will post an update shortly.

**Comment by Kraego** [comment]
We have the same Issue, glad to hear that there is progress on this problem

**Comment by fd0cwp** [comment]
Installed version: 2.3.21 
Issue is still there after starting a session and opening the link in a new window.

**Comment by MOlausson** [comment]
Fixed in #105.
