### ISSUE TITLE
Cant create new estimate session in Azure DevOps

### ISSUE THREAD

**Issue by rpc64** [microsoft/azure-boards-estimate#39]
Hello,
 
I would like to use the extension Estimate to do the Planning Poker in Azure DevOps.
Unfortunately I cannot create new estimation sessions, since the create button does not become active.
 
Do you have any hint?
Thanks,
 
Robert
 
 
![Create new Estimate Session](https://user-images.githubusercontent.com/91785518/135715439-90e31e32-0dd6-4b97-a614-56b99e910a36.jpg)

![Extension Estimate](https://user-images.githubusercontent.com/91785518/135715058-e8cc554a-236d-4ba1-9b29-1439c3041dd5.jpg)

**Comment by MOlausson** [comment]
@rpc64, for this scenario to work you need to start creating the Estimate session from the backlog or a query as the text under the "work items" title says. This way the extension gets the information needed to create the session:

![image](https://user-images.githubusercontent.com/7904771/135762536-eae9745b-b76f-4dd6-aa44-f1dd31f82de8.png)

I'll add a task to improve the documentation for this.

**Comment by rpc64** [comment]
@MOlausson, thanks for your support.
With your hint I am now able to create the estimate sessions.
