### ISSUE TITLE
User cannot create Session

### ISSUE THREAD

**Issue by jovery90** [microsoft/azure-boards-estimate#42]
One of my coworkers is unable to create a session with Estimate, dropdowns seem to be disabled for her (her Azure permissions are equivalent to other users that work, as Project Administrators in the Azure Project).

Are there any other settings on a user account that could be causing this?

**Comment by MOlausson** [comment]
@jovery90 is it only one person seeing this? Are you on Azure DevOps service or self-hosted?

**Comment by MOlausson** [comment]
@jovery90 any update on this? Closing it now due to inactivity but feel free to reopen!
