### ISSUE TITLE
Acceptance Criteria is unformatted in projects that use the XML template, works for inherited.  

### ISSUE THREAD

**Issue by JThomas77** [microsoft/azure-boards-estimate#44]
We have several projects that use this extension. Currently all inherited based processes template projects are showing the AC correctly. The projects with XML based templates are showing unformatted HTML text for the AC in the user story cards when you open the session.

**Comment by MOlausson** [comment]
@JThomas77 sounds like there's a difference in the data format, we'll take a look next week.

**Comment by JThomas77** [comment]
Hello, Did you have any findings after looking into this?

**Comment by MOlausson** [comment]
@JThomas77 we're looking at the different enhancements in the backlog for the next update, adding this to the queue.

**Comment by AminTi** [comment]
resolved
