### ISSUE TITLE
Hello, I want to estimate features and epic also (different from user stories), is it possible?

### ISSUE THREAD

**Issue by nerialex** [microsoft/azure-boards-estimate#46]
Hello, I want to estimate features and epic also (different from user stories), is it possible?

**Comment by MOlausson** [comment]
@nerialex yes you can! Just make sure to set the correct fields (i.e. Effort) in the Estimate settings.

![image](https://user-images.githubusercontent.com/7904771/144914677-7cf3f8cc-5854-4266-8e9e-d5fa428f4215.png)
