### ISSUE TITLE
Extension no longer works after "Moved extension to new home" update

### ISSUE THREAD

**Issue by Blackbaud-MaryRudisill** [microsoft/azure-boards-estimate#6]
Version 2.3.0 just got pushed to our Azure DevOps. 
The extension Hub page (list of Sessions) still loads (although I am seeing errors in Chrome tools), but we can no longer drill into any specific Sessions. Page never finishes loading and seeing the following error:

POST https://msdevlabs-estimate-backend.azurewebsites.net//estimate/negotiate?sessionId=...      net::ERR_CONNECTION_RESET

I see in the code that 
`const baseUrl = "https://estimate-backend.azurewebsites.net/";`
changed to
`const baseUrl = "https://msdevlabs-estimate-backend.azurewebsites.net/";`

I'm assuming there is an issue with us accessing the new baseUrl.
Thanks.

**Comment by MOlausson** [comment]
Hi @Blackbaud-MaryRudisill. Thanks for letting us now, we'll look into this. Have you tried a hard reload of the extension? Do you get the same error if you start a new session?

**Comment by Blackbaud-MaryRudisill** [comment]
Aha!  I restarted the browser and force loaded the page and it appears to be working. Sorry about that. I'm embarrassed that I didn't try turning it off and on again before filing this. Thanks.

**Comment by Blackbaud-MaryRudisill** [comment]
Do y'all close this or do you want me to?

**Comment by MOlausson** [comment]
Ah, good to hear it's working for you. I'll close the issue for you now.
