### ISSUE TITLE
Show how many votes are present/missing

### ISSUE THREAD

**Issue by hangy** [microsoft/azure-boards-estimate#67]
In today's refinement meeting, @LiTe1991 had the idea that it would be useful for a Scrum master to know how many people are in the current session, and how many of those have voted on the active item, already. This way, they would not have to count the people/votes manually to know when the estimation for the item is complete.

**Comment by MOlausson** [comment]
@hangy thanks, good suggestion. We'll triage and I'll come back with an update later this week.
