### ISSUE TITLE
v2.3.13 results in "API Version out of Range" message

### ISSUE THREAD

**Issue by klsgrtx** [microsoft/azure-boards-estimate#73]
Our on-prem instance of ADO is on v2019.1.1
ASURE-BOARDS-ESTIMATE was working in our installation until this morning when it was updated to v2.3.13.

We now get the following message when our users try to access their estimates:

"Could not load session: The requested REST API version of 5.2 is out of range for this server. The latest REST API version this server supports is 5.1."

Is there a way to rollback to previous version?
Is there a way to edit a config file to point to APIv5.1?

**Comment by MOlausson** [comment]
@klsgrtx, thanks for reporting. Could you help us track this down by checking the browser network log (f12 in the browser), and the console log for errors? There should be an error telling us which api that's failing for you.

**Comment by fwdslashnet** [comment]
Same issue for me. 
 
 We are using `AzureDevOps2019.Update1`. 
 
 # Session
When I click on a session I'm shown this error. 
![image](https://user-images.githubusercontent.com/8642458/152330703-b99947a6-0369-4886-896e-a8764fa4fd35.png)

The output in the Dev Tools Console 
```
 at d 
 at Zn 
 TFS.WebApi.Exception: The requested REST API version of 5.2 is out of range for this server. The latest REST API version this server supports is 5.1.
    at Object.<anonymous> (https://myazureserver/_apis/public/gallery/publisher/ms-devlabs/extension/estimate/2.3.13/assetbyname/build/static/js/1.cc5b2ff6.chunk.js:1:832356)
    at https://myazureserver/_apis/public/gallery/publisher/ms-devlabs/extension/estimate/2.3.13/assetbyname/build/static/js/1.cc5b2ff6.chunk.js:1:830903
    at Object.next (https://myazureserver/_apis/public/gallery/publisher/ms-devlabs/extension/estimate/2.3.13/assetbyname/build/static/js/1.cc5b2ff6.chunk.js:1:831008)
    at a (https://myazureserver/_apis/public/gallery/publisher/ms-devlabs/extension/estimate/2.3.13/assetbyname/build/static/js/1.cc5b2ff6.chunk.js:1:829753)
P @ utils.js:262
/COLLECTION/_apis/projects/PROJECT:1 
        
       Failed to load resource: the server responded with a status of 400 (Bad Request)
```

##  Teams
### General 
```
Request URL: https://myazureserver/PROJECT/_apis/projects/b62e367d-d4bb-4c78-9349-b91b8d411eca/teams?%24mine=false&%24top=1000&%24skip=0
Request Method: GET
Status Code: 400 Bad Request
Remote Address: 999.99.99.999:999
Referrer Policy: strict-origin-when-cross-origin
```
### Request Headers

`application/json;api-version=5.2-preview.3;excludeUrls=true;enumsAsNumbers=true;msDateFormat=true;noArrayWrap=true`

# Settings
Also, we are encountering similar issues when we try and look at the settings. Settings does not load.

![image](https://user-images.githubusercontent.com/8642458/152331880-49b7e0d8-b9c5-4403-9022-1b4793ae399f.png)

We get a processconfiguration error:
### General
```
Request URL: https://myazureserver/PROJECT/b62e367d-d4bb-4c78-9349-b91b8d411eca/_apis/work/processconfiguration
Request Method: GET
Status Code: 400 Bad Request
Remote Address: 999.99.99.999:999
Referrer Policy: strict-origin-when-cross-origin
```
### Request Header
`application/json;api-version=5.2-preview.1;excludeUrls=true;enumsAsNumbers=true;msDateFormat=true;noArrayWrap=true`

**Comment by MOlausson** [comment]
We've can repro the issue and looking into it now. Thanks for the detailed report @fwdslashnet !

**Comment by MOlausson** [comment]
@fwdslashnet @klsgrtx we just released 1.2.14 now where we've rolled back to an earlier version of the AzDO sdk that should support Azure DevOps 2019. Great if you can upgrade and let us know how if you still see any issues.

**Comment by klsgrtx** [comment]
My users have reported that the extension is working normally.ThanksSent from my Galaxy
-------- Original message --------From: Mathias Olausson ***@***.***> Date: 2/8/22  12:51 PM  (GMT-06:00) To: microsoft/azure-boards-estimate ***@***.***> Cc: Ken ***@***.***>, Mention ***@***.***> Subject: Re: [microsoft/azure-boards-estimate] v2.3.13 results in "API Version out of Range" message (Issue #73) 
@fwdslashnet @klsgrtx we just released 1.2.14 now where we've rolled back to an earlier version of the AzDO sdk that should support Azure DevOps 2019. Great if you can upgrade and let us know how if you still see any issues.

**Comment by MOlausson** [comment]
@klsgrtx thanks for confirming!

**Comment by fwdslashnet** [comment]
# Confirmed Fixed 
@MOlausson Thanks, we can confirm that the version is at 1.2.14 (latest)
![image](https://user-images.githubusercontent.com/8642458/153377755-c9f99b43-26a0-4c0b-9217-3e68674d176d.png)

# Sessions
Session dashboard is loading, as are the sessions. 
![image](https://user-images.githubusercontent.com/8642458/153378222-163d4f09-ca5d-4ea5-949c-9ed789b25a2a.png)

# Settings
The settings sidebar is also loading as expected. 
![image](https://user-images.githubusercontent.com/8642458/153378129-53be09bd-8172-4501-a417-d9cb8f68088e.png)

Many thanks for your assistance, much appreciated.
