### ISSUE TITLE
Estimate data is not loading after migration to cloud

### ISSUE THREAD

**Issue by deepuhnb** [microsoft/azure-boards-estimate#74]
I am migrating the collection from ADO on-premise to ADO SAAS. The Estimate data is not loading after the collection is successfully migrated. I have the Estimate plugin that shows data in the on-premise collection, which are not showing up in the migrated organization.

Please let me know if there is any workaround to export and import the retrospective data to SAAS organization.

Migration is performed using the Azure SQL VM Migration approach using the latest version of the Microsoft migration tool.

**Comment by MOlausson** [comment]
@deepuhnb have you re-installed the extension? After migrating with the migrator you need to reinstall all extensions, so wanted to check this before we dig into troubleshootning.

**Comment by deepuhnb** [comment]
After migration, I have manually installed all the plugins, MS Migration tool does not install plugins. I also re-installed no luck. I have faced the same issue with a few other plugins which are Estimate, Retrospective able to fix the data using the rest API calls. 
If you can provide the details of rest API export and import data that will be also usefull.
Thank you

**Comment by deepuhnb** [comment]
Please ignore my earlier comment the comment was for the "Team Calendar" plugin from MS. We resolved the issue for Estimate and retrospective plugins using Rest calls.
Thank you
