### ISSUE TITLE
Being signed out when accessing a session

### ISSUE THREAD

**Issue by dusoxr** [microsoft/azure-boards-estimate#83]
Dear team,

after recent update once accessing the session we are being signed-out which makes the plugin unusable. 
Even after submitting the correct credentials it is not working.

Please advice. Thank you!

Julius

**Comment by icolovic** [comment]
We have a same problem. Extension in installed on Azure DevOps server on the premises.
Version of extension is 2.3.14.

**Comment by MOlausson** [comment]
@dusoxr @icolovic can you describe the scenario in a bit more detail? When is this happening for you?

**Comment by dusoxr** [comment]
@MOlausson steps are following:
(I have been using VPN to access the plugin)

1. I access the Estimate plugin
2. All my sessions are listed
3. I click on any of the sessions we have been using for around a year now
4. Loading work items... Connecting to server...
5. Getting basically signed out with the browser dialog box asking for my login details "Your connection to this site is not private"

**Comment by dusoxr** [comment]
@MOlausson has there been any update please?

**Comment by edisonas** [comment]
Something similar happening to me after extension upgrade, when accessing estimate it's asking for credentials to login, and it never ends, after entering correct credentials it's asking to enter again, and in that case i'm unable to reach sessions which are under estimate section. 
Any help would be appreciated!

**Comment by dusoxr** [comment]
@MOlausson is the support for this still ongoing or we should start looking for another plugin?

**Comment by MOlausson** [comment]
Hi all, we have a new release coming this week. Let's see if that resolves the issue, else we'll dig into this again.

**Comment by MOlausson** [comment]
> @MOlausson is the support for this still ongoing or we should start looking for another plugin?

It's indeed supported but sharing time between other commitments sometimes cause a delay. Which AzDO Server version are you using? 2020?

**Comment by DanielRatvai** [comment]
Hallo, 

@MOlausson 
We have the same issue. I have collection admin right, so I'm sure I should have the necessary permission. Everybody is affected, all of us get this pop up window. (If we click on it around 10 times, the pop up window will be gone and we can use the extension.)

**AzDO server: Azure DevOps Server 2019.1.1 Patch 13 Version 17.153.32118.3**


![Estimate_Issue](https://user-images.githubusercontent.com/78346463/165041234-71c4d3c1-e266-4a40-b8eb-4a0f05a4470b.png)

Could you please help us out? 

Thanks,
Daniel

**Comment by dusoxr** [comment]
> Hi all, we have a new release coming this week. Let's see if that resolves the issue, else we'll dig into this again.

@MOlausson  is this the version you are referring to? If yes the issue still persists :(

![Screenshot 2022-04-25 at 2 55 30 PM](https://user-images.githubusercontent.com/4050772/165075809-0d5a8e58-e41e-4ca4-92a3-604e449aa8fa.png)

**Comment by edisonas** [comment]
@MOlausson , when new version going to happen?

**Comment by AminTi** [comment]
It should be fixed now, please do not use VPN.
