### ISSUE TITLE
Work item header title link only links to the first work item in the list

### ISSUE THREAD

**Issue by Sean-Blackbaud** [microsoft/azure-boards-estimate#88]
When there is a list of work item cards, the title link is the same for all of them and is for the first work item in the list.

I looked into this a little bit, but I'm not a React developer.  It seems like the recent switch to get the URL with the `ILocationService` in the [workItemHeader.tsx](https://github.com/microsoft/azure-boards-estimate/blob/main/src/components/workitems/workItemHeader.tsx) is the cause, and I suspect that there's some await issue going on.  Again, no React experience but maybe the location service is acting as a singleton instead of running for each component instance?  Or perhaps there's some odd React stuff happening.

**Comment by hangy** [comment]
This might be a duplicate of #77

**Comment by MOlausson** [comment]
@hangy @Sean-Blackbaud closing this as a duplicate of #77 .
