### ISSUE TITLE
View another work item without changing everyone's view

### ISSUE THREAD

**Issue by strout** [microsoft/azure-boards-estimate#95]
During a live estimation session, I'd like to be able to view a work item other than the current active one (preferably a link I can open in another tab) without changing everyone's view.

Example use cases:
* Open the next item as discussion is winding down on the current item, to read ahead.
* Refer back to a previous work item from the session without clearing already-made votes.
* Open all work items for the session in tabs. (Fixing #77 would help with this, since I usually do it at the beginning of the estimation session.)

Currently I have to remember or write down the work item number, open a new tab, and navigate to it manually. I can't use the clipboard to help, because highlighting an inactive work item's number or name makes it active.

Thank you for considering this enhancement request.

**Comment by AminTi** [comment]
Hi @strout  we released an update today. We resolved #77

**Comment by AminTi** [comment]
resolved
