### ISSUE TITLE
Workitem links on estimate linked to wrong item

### ISSUE THREAD

**Issue by tobymilne-haven** [microsoft/azure-boards-estimate#98]
Hi,
We are having a problem with links on estimates - we are running v2.3.14.
The links in the estimates all appear to point at one item, not the currently selected item. See attached screenshot where i am hovering over the story 26710 link, and the url is pointing to 26712.

![estimate_link_error](https://user-images.githubusercontent.com/58178238/157682934-efe0d077-1e0b-4b0d-987f-99d31710232a.png)

**Comment by MOlausson** [comment]
Hi @tobymilne-haven, thanks for reporting. This is probably the same issue as in #77 which is fixed and is planned to be released tomorrow. Keep an eye out for the update and let me know if it works post v2.3.16 where the fix is first included.

**Comment by tobymilne-haven** [comment]
Thanks - will do!

**Comment by MOlausson** [comment]
@tobymilne-haven FYI v2.3.17 was released today - hope it fixes your scenario.

**Comment by tobymilne-haven** [comment]
Yep just checked a few sessions and all links working OK. Thanks for letting me know!
